### ISSUE TITLE
Restoring from snapshot fails executable file not found in $PATH

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1059]
**Environmental Info:**
RKE2 Version: 
* `v1.21.1-rc1+rke2r1`

Node(s) CPU architecture, OS, and Version: 
Ubuntu 20.04

Cluster Configuration:
Single node cluster

**Describe the bug:**
Restoring from snapshot fails with Containerd Exited: exec: "containerd": executable file not found in $PATH, exiting kubelet 

**Steps To Reproduce:**
Create a single node cluster
Take snapshot
Stop rke2 service
Run killall 
Restore using the snapshot
```
rke2 server \
--cluster-reset \
--cluster-reset-restore-path=/var/lib/rancher/rke2/server/db/snapshots/on-demand-<unix-timestamp
```

**Expected behavior:**
Reset should be run and cluster-reset msg is expected to be seen on the console

**Actual behavior:**
Errors with Containerd Exited: exec: "containerd": executable file not found in $PATH, exiting kubelet  and panic

**Additional context / logs:**
```
sudo rke2 server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-39-67-1621896967
WARN[0000] not running in CIS mode                      
INFO[0000] starting kubelet to clean up old static pods 
INFO[0005] Containerd Exited: exec: "containerd": executable file not found in $PATH, exiting kubelet 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4be89b]

goroutine 1 [running]:
os.(*Process).signal(0x0, 0x70cc4b8, 0x9be7958, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:63 +0x3b
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:135
os.(*Process).kill(...)
	/usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
	/usr/local/go/src/os/exec.go:120
github.com/rancher/rke2/pkg/rke2.removeOldPodManifests(0x66d7963, 0x15, 0xc001699a70, 0x1, 0x0, 0x0)
	/source/pkg/rke2/rke2.go:229 +0x945
github.com/rancher/rke2/pkg/rke2.setup(0xc000a4b4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/source/pkg/rke2/rke2.go:164 +0x8a5
github.com/rancher/rke2/pkg/rke2.Server(0xc000a4b4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/source/pkg/rke2/rke2.go:48 +0x6b
github.com/rancher/rke2/pkg/cli/cmds.ServerRun(0xc000a4b4a0, 0x0, 0x0)
	/source/pkg/cli/cmds/server.go:143 +0x98
github.com/urfave/cli.HandleAction(0x57f1f00, 0x68fece0, 0xc000a4b4a0, 0xc000a4b4a0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x6693772, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x66da585, 0x15, 0xc0017b8a50, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc0009afc00, 0xc000a52c00, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
	/source/main.go:20 +0x714
```

**Comment by ShylajaDevadiga** [comment]
Validated fix on rke2 version v1.21.1-rc2+rke2r1, restore from snapshot is successful
```
sudo rke2 server --cluster-reset --cluster-reset-restore-path=/var/lib/rancher/rke2/server/db/snapshots/on-demand-ip-172-31-15-127-1622700212
WARN[0000] not running in CIS mode                      
INFO[0000] Running temporary containerd /var/lib/rancher/rke2/bin/containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/containerd 
INFO[0000] Running temporary kubelet /var/lib/rancher/rke2/bin/kubelet --fail-swap-on=false --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests 
...
...
INFO[0080] Failed to test data store connection: context deadline exceeded 
INFO[0082] Updating load balancer server addresses -> [172.31.15.127:6443 ] 
INFO[0082] Updating load balancer server addresses -> [172.31.15.127:9345 127.0.0.1:9345] 
INFO[0082] Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes 
```
