### ISSUE TITLE
Kubelet Fails to Start

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#128]
**Environment**
rke2 -v
rke2 version v1.18.4-alpha20-rke2 

NodeOS and Arch:
Ubuntu 20.04, amd 64, 20GB hard disk

**Issue**

Installation hangs with alpha20 with INSTALL_RKE2_CIS_MODE is set to true
Kubelet is exited

**Steps to reproduce**
1. wget https://raw.githubusercontent.com/rancher/rke2/master/install.sh
2. chmod u+x install.sh 
3. INSTALL_RKE2_VERSION=v1.18.4-alpha20+rke2 INSTALL_RKE2_CIS_MODE=true  ./install.sh

**Logs**
```
Jul 27 17:23:04 ip-172-31-9-45 rke2[2112]: {"level":"warn","ts":"2020-07-27T17:23:04.010Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-d47e6ce9-bd0c-411d-87b6->
Jul 27 17:23:04 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:04Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Jul 27 17:23:06 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:06Z" level=error msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkuberne>
Jul 27 17:23:06 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:06Z" level=error msg="Kubelet exited: exit status 255"
Jul 27 17:23:08 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:08Z" level=info msg="Waiting for etcd server to become available"
Jul 27 17:23:11 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:11Z" level=error msg="Unable to watch for tunnel endpoints: Get \"https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkuberne>
Jul 27 17:23:12 ip-172-31-9-45 rke2[2112]: time="2020-07-27T17:23:12Z" level=error msg="Kubelet exited: exit status 255"
```

**Additional info**
```
E0727 16:54:46.782777    2142 controller.go:136] failed to ensure node lease exists, will retry in 400ms, error: Get "https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/ip-172-31-9-45?timeout=10s": dial tcp 127.0.0.1:6443: connect: connection refused
I0727 16:54:46.792947    2142 policy_none.go:43] [cpumanager] none policy: Start
F0727 16:54:46.793496    2142 kubelet.go:1383] Failed to start ContainerManager invalid kernel flag: vm/overcommit_memory, expected value: 1, actual value: 0
goroutine 234 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc000126001, 0xc001390000, 0x900, 0x2710)
        /go/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:875 +0xb8
```
Memory:
```
free -h
              total        used        free      shared  buff/cache   available
Mem:          3.8Gi       250Mi       488Mi       0.0Ki       3.1Gi       3.4Gi
Swap:            0B          0B          0B
root@ip-172-31-9-45:~# 
```

**Comment by briandowns** [comment]
Issue resolved in #129

**Comment by ShylajaDevadiga** [comment]
@briandowns As a non root user seeing a small issue with permission.
```
ubuntu@ip-172-31-6-149:~$ INSTALL_RKE2_VERSION=v1.18.4-alpha21+rke2 INSTALL_RKE2_CIS_MODE=true ./install.sh
sysctl: permission denied on key "vm.panic_on_oom"
```
Works as root user.

**Comment by briandowns** [comment]
Which version of the install script are you using?

**Comment by rancher-max** [comment]
I've tried with both alpha21 and master install scripts and see the same error:
```
# Alpha 21
$ curl -sfL https://raw.githubusercontent.com/rancher/rke2/v1.18.4-alpha21+rke2/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha21+rke2 sh -
sysctl: permission denied on key "vm.panic_on_oom"

# Master
$ curl -sfL https://raw.githubusercontent.com/rancher/rke2/master/install.sh | INSTALL_RKE2_VERSION=v1.18.4-alpha19+rke2 INSTALL_RKE2_CIS_MODE=true sh -
sysctl: permission denied on key "vm.panic_on_oom"
```

**Comment by davidnuzik** [comment]
Sorry I thought this was kubelet failing to start issue? Should this belong in a different issue or be a new issue?

**Comment by briandowns** [comment]
At this point, yes, this is a different issue with some install script enviornment setup ordering being different from the k3s install and missing a couple calls to sudo. PR coming in.

**Comment by briandowns** [comment]
PR that resolves perm issue: #130

**Comment by rancher-max** [comment]
You're right. This thread belongs in #97. 

#### This issue itself has been validated

- Kubelet starts successfully with root user in `alpha21` and cluster comes up as active. 
- CIS mode functional in all ndoes when joining both new server and agent nodes

**Comment by ShylajaDevadiga** [comment]
Logs do not have vm.overcommit_memory set to 1
```
journalctl |grep "sysctl" |grep "vm"
Jul 27 20:13:23 ip-172-31-6-149 sudo[825851]:     root : TTY=pts/0 ; PWD=/root ; USER=root ; COMMAND=/usr/sbin/sysctl -q -w vm.panic_on_oom=0
root@ip-172-31-6-149:~# 
```
Probably parameter is missing here https://github.com/rancher/rke2/blob/102f2f6b7fca78919e1a8c95a4b275e4c26f3760/pkg/cli/cmds/root.go#L46

**Comment by ShylajaDevadiga** [comment]
Closing issue. #130 addresses this issue.
