### ISSUE TITLE
Snapshot restoration fails in Rancher downstream RKE2 clusters

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#1685]
**Summary:**
The system agent appears to have similar behavior to https://github.com/rancher/system-agent/issues/49 when I attempt to take a snapshot - I will see an attempt to restore from snapshot in the agent logs that will fail, and it will seemingly infinitely keep trying restoration.

**Environment:**
Rancher version: v2.6-head `f5761521d` pulled at 8/20/21 9:25 am Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc6+rke2r2

**Steps to Reproduce:**
1. In rancher, provision any RKE2 cluster - such as with any node driver or a custom cluster. 1-node cluster is fine. Use default settings for the cluster.
2. When the cluster is fully ready, take a snapshot.
3. After the snapshot is fully ready/done, try to restore

 
**Expected Result:**

**Actual Result:**
You will see an error in the Rancher UI after a minute or two after restoration:
![image](https://user-images.githubusercontent.com/45179589/130282690-86f4a25b-f83b-4d5e-ab65-b6ea448dfceb.png)

The rancher-system-agent logs seem to loop trying restore again and again. The logs mention a stacktrace after a while (could take 15+minutes) and a pod is orphaned (kubelet I believe based on what I see in the logs).

stack trace logs snippet:
```
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: E0820 19:09:44.362892   32267 runtime.go:78] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: goroutine 231 [running]:"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/runtime.logPanic(0x43608a0, 0x724f430)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: panic(0x43608a0, 0x724f430)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/usr/local/go/src/runtime/panic.go:965 +0x1b9"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateDevicePath(0xc00013dc80, 0xc001683c88)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:598 +0x41"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateStates(0xc00013dc80, 0xc001683c88, 0xc0003504c0, 0x40)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:629 +0x50"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).syncStates(0xc00013dc80)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:434 +0x3d7"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).sync(0xc00013dc80)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:348 +0x4e"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.func1()"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:158 +0x118"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d9c200)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d9c200, 0x5326a00, 0xc000cf3ad0, 0x44fba01, 0xc0000a40c0)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d9c200, 0x5f5e100, 0x0, 0x1, 0xc0000a40c0)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/apimachinery/pkg/util/wait.Until(...)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0xc00013dc80, 0xc0000a40c0)"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:146 +0x5f"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run"
Aug 20 19:09:44 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:44Z" level=info msg="[stderr]: \t/go/src/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:272 +0x1df"
```

errors and orphan pod mentioned logs snippet:
```
Aug 20 19:09:46 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:46Z" level=info msg="[stderr]: E0820 19:09:46.232555   32267 kubelet_volumes.go:179] \"There were many similar errors. Turn up verbosity to see them.\" err=\"orphaned pod \\\"d06e4af3-2421-491a-ad02-ee5b5745df80\\\" found, but failed to rmdir() volume at path /var/lib/kubelet/pods/d06e4af3-2421-491a-ad02-ee5b5745df80/volumes/kubernetes.io~configmap/config-volume: directory not empty\" numErrs=3"
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=info msg="[stderr]: time=\"2021-08-20T19:09:47Z\" level=info msg=\"Static pod cleanup completed successfully\""
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=info msg="[stderr]: time=\"2021-08-20T19:09:47Z\" level=info msg=\"Starting rke2 v1.21.3-rc6+rke2r2 (0a58cb4f9b947dae97f06130bf6764789d93994c)\""
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=info msg="[stderr]: time=\"2021-08-20T19:09:47Z\" level=info msg=\"Managed etcd cluster bootstrap already complete and initialized\""
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=info msg="[stderr]: time=\"2021-08-20T19:09:47Z\" level=info msg=\"Checking if S3 bucket  exists\""
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=info msg="[stderr]: time=\"2021-08-20T19:09:47Z\" level=fatal msg=\"starting kubernetes: preparing server: start managed database: Bucket name cannot be empty\""
Aug 20 19:09:47 dave-tryrestoreagain-pool1-16cb527c-ghj48 rancher-system-agent[11819]: time="2021-08-20T19:09:47Z" level=error msg="error syncing 'fleet-default/dave-tryrestoreagain-bootstrap-template-qpg4g-machine-plan': handler secret-watch: error applying plan: error executing instruction 4: exit status 1, requeuing"
```

**Additional Info:**
Full rancher-system-agent logs (snapshot first mentioned on line 6007, first cluster restore happens (only time user asks) at line 11935)
[rancher-system-agent1.log](https://github.com/rancher/rke2/files/7023726/rancher-system-agent1.log)

Full rke2-server logs (I didn't find anything useful in these logs)
[rke2-server1.log](https://github.com/rancher/rke2/files/7023727/rke2-server1.log)

_**Please let me know if I can assist in any way, such as by providing a Rancher server / rke2 downstream cluster to reproduce with or additional logs, etc**_

**Comment by davidnuzik** [comment]
This may not be 100% reproducable - you may need to try a couple of times at most. I did see that after an hour or more two of four clusters came up according to the Rancher UI:
![image](https://user-images.githubusercontent.com/45179589/130284565-e8dd10b9-1cc0-4aa0-8c3c-69db95ba9fa9.png)

I highly suspect that the differences in config make no difference here -- in fact in the picture you'll see the 1st cluster works - it's cluster config is a carbon copy of the 4th cluster "dave-tryrestoreagain".

**Comment by Jono-SUSE-Rancher** [comment]
Just putting this here that this is a duplicate https://github.com/rancher/system-agent/issues/49 issue that I believe @Oats87 is working on in `system-agent`

**Comment by Oats87** [comment]
@Jono-SUSE-Rancher Looking at this issue, I do not believe it relates to https://github.com/rancher/system-agent/issues/49

This looks like the etcd restore plan is not properly populating the S3 environment variables. I believe potentially it may be caused by the addition of the "prefix" here: https://github.com/rancher/rancher/blob/master/pkg/provisioningv2/rke2/planner/etcdrestore.go#L29 note it is missing here: https://github.com/rancher/rancher/blob/master/pkg/provisioningv2/rke2/planner/etcdcreate.go#L28-L29

**Comment by davidnuzik** [comment]
This is local. local restore does not work. the issue does not mention s3
There are various s3 issues but snapshot restore does not work at all in Rancher for local. (s3 too but seemingly for different reasons)

**Comment by erikwilson** [comment]
There are two problems:

1. the panic is caused by a stale kubelet directory that needs to be cleaned up
2. once kubelet is cleaned up it appears that restore through the rancher ui is triggering a restore which expects credentials even though this is a local restore

**Comment by cjellick** [comment]
> 2. once kubelet is cleaned up it appears that restore through the rancher ui is triggering a restore which expects credentials even though this is a local restore

@briandowns - thoughts on what would get a restore into this situation?

**Comment by cjellick** [comment]
> 1. the panic is caused by a stale kubelet directory that needs to be cleaned up

Trying to piece that panic together, I wonder if the kubelet is somehow in standalone mode or being recognized as such
I see this log line:

> 12010 -20T18:19:51Z" level=info msg="[stderr]: I0820 18:19:51.880297   20741 server.go:573] \"Standalone mode, no API client\""

and the panic is around trying to get the client

**Comment by briandowns** [comment]
Can someone supply the plan including the command system agent is running when this is observed? I haven't seen this in stand alone.

**Comment by briandowns** [comment]
It appears as though the cluster is generating a plan for system-agent that includes S3 flags. 1 to enable S3 and one for the bucket. I confirmed with @davidnuzik that the Rancher install is barebones and no S3 configuration for backup/restore.

```sh
root@dave-1node-repro1685-pool1-46807efc-wdbvt:/var/lib/rancher/agent/applied# cat 20210825-020322 | jq -r '.Plan.instructions[4]'
{
  "name": "restore",
  "args": [
    "server",
    "--cluster-reset",
    "--cluster-reset-restore-path=on-demand-dave-1node-repro1685-pool1-46807efc-wdbvt-1629855943",
    "--etcd-s3",
    "--etcd-s3-bucket="
  ],
  "command": "rke2"
}
```

**Comment by Oats87** [comment]
It is very likely that what is causing this is: https://github.com/rancher/rancher/blob/master/pkg/provisioningv2/rke2/planner/etcdrestore.go#L29

PR incoming to remove this on the Rancher side.

**Comment by deniseschannon** [comment]
As this was identified as a Rancher fix, not RKE2 fix. I'd like to propose closing but not sure of the RKE2 process.

**Comment by Jono-SUSE-Rancher** [comment]
Is it something that we don't have to tackle for 2.6? Either way I am fine with transferring it and then we can address it for 2.6.1 or 2.6.2 depending on severity.
