### ISSUE TITLE
Windows uninstall script does not properly cleanup all resources to allow reuse of AWS instance

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1754]
**Environmental Info:**
RKE2 Version: 

v1.21.4-rc1+rke2r3

Node(s) CPU architecture, OS, and Version: 

Windows 2019 

Cluster Configuration:

1 server 
1 windows agent

**Describe the bug:**

After running the uninstall script on a windows node, then trying to rerun the rke2 binary, this error occurs:
```
time="2021-09-02T21:31:17Z" level=info msg="Generating HNS networks, please wait"
(does the screen thing, then this)

panic: router only implemented in linux

goroutine 1 [running]:
github.com/google/gopacket/routing.New(...)
        /go/pkg/mod/github.com/google/gopacket@v1.1.19/routing/other.go:14
github.com/rancher/rke2/pkg/windows.setMetaDataServerRoute(0xc001626190, 0xc, 0x0, 0x0)
        /source/pkg/windows/calico.go:478 +0xcb
github.com/rancher/rke2/pkg/windows.generateCalicoNetworks(0x7ff6b9ee1e4b, 0x5, 0xc0021855c0, 0x1)
        /source/pkg/windows/calico.go:310 +0x19f
github.com/rancher/rke2/pkg/windows.(*Calico).Setup(0x7ff6bd310fb8, 0x7ff6ba93c9d8, 0xc001238c00, 0x7ff6b9f27a17, 0x15, 0xc000600400, 0xc001ba6b40, 0xc0017ac000, 0x1b7, 0x19)
        /source/pkg/windows/calico.go:111 +0x71d
```

**Steps To Reproduce:**

- Install rke2 on windows agent
- Run uninstall:
```
Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/rancher/rke2/master/bundle/bin/rke2-uninstall.ps1 -OutFile c:\usr\local\bin\uninstall-rke2.ps1
c:\usr\local\bin\uninstall-rke2.ps1
```
- Rerun rke2 on windows agent

**Expected behavior:**

This should allow for reinstalling rke2 fresh on the instance

**Actual behavior:**

A panic occurs 

**Additional context / logs:**

The panic is shown when running via the binary. If running the service, it appears to just constantly restart.

**Comment by brandond** [comment]
I think @phillipsj was saying they always reboot after uninstalling because they haven't got the script cleaning everything up yet.

**Comment by phillipsj** [comment]
No need to reboot.
