### ISSUE TITLE
Uninstall and reinstall on windows 2022 hits router panic

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#1954]
**Environmental Info:**
RKE2 Version: 

v1.22.2-rc1+rke2r1

Node(s) CPU architecture, OS, and Version: 

```
PS C:\Users\Administrator> Get-ComputerInfo

WindowsBuildLabEx                                       : 20348.1.amd64fre.fe_release.210507-1500
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 10/13/2021 1:07:56 AM
WindowsProductId                                        : 00454-60000-00001-AA008
WindowsProductName                                      : Windows Server 2022 Datacenter
WindowsRegisteredOrganization                           : Amazon.com
WindowsRegisteredOwner                                  : EC2
WindowsSystemRoot                                       : C:\Windows
WindowsVersion                                          : 2009
```
Using AWS: `Windows_Server-2022-English-Full-ContainersLatest-2021.09.15 - ami-0d55df877a8eada89`

Cluster Configuration:

server running calico, windows agent running calico

**Describe the bug:**

Initial install worked fine. After running the uninstall script, deleting the node from the cluster, and trying to reinstall, I see this error:
```
time="2021-10-13T23:32:34Z" level=info msg="Generating HNS networks, please wait"
panic: router only implemented in linux

goroutine 1 [running]:
github.com/google/gopacket/routing.New(...)
        /go/pkg/mod/github.com/google/gopacket@v1.1.19/routing/other.go:14
github.com/rancher/rke2/pkg/windows.setMetaDataServerRoute(0xc00177a5a0, 0xd, 0x0, 0x0)
        /source/pkg/windows/calico.go:478 +0xcb
github.com/rancher/rke2/pkg/windows.generateCalicoNetworks(0x7ff7d47b3063, 0x5, 0xc0029055c0, 0x1)
        /source/pkg/windows/calico.go:310 +0x19f
github.com/rancher/rke2/pkg/windows.(*Calico).Setup(0x7ff7d7d38d68, 0x7ff7d52551d8, 0xc0019e8ac0, 0x7ff7d47f8d53, 0x15, 0xc000101400, 0xc001ac7440, 0xc0014a4000, 0x207, 0x19)
        /source/pkg/windows/calico.go:111 +0x717
github.com/rancher/rke2/pkg/pebinaryexecutor.(*PEBinaryConfig).Bootstrap(0xc0017a6900, 0x7ff7d52551d8, 0xc0019e8ac0, 0xc000101400, 0xc0014180c0, 0x54, 0x0, 0x0, 0x0, 0x0, ...)
        /source/pkg/pebinaryexecutor/pebinary.go:110 +0x38f
github.com/rancher/k3s/pkg/daemons/executor.Bootstrap(...)
        /go/pkg/mod/github.com/rancher/k3s@v1.22.3-0.20211007194742-737f722315b9/pkg/daemons/executor/executor.go:89
github.com/rancher/k3s/pkg/agent.run(0x7ff7d52551d8, 0xc0019e8ac0, 0xc0014180c0, 0x54, 0x0, 0x0, 0x0, 0x0, 0xc0012fdc89, 0x19, ...)
        /go/pkg/mod/github.com/rancher/k3s@v1.22.3-0.20211007194742-737f722315b9/pkg/agent/run.go:71 +0x2d5
github.com/rancher/k3s/pkg/agent.Run(0x7ff7d52551d8, 0xc0019e8ac0, 0xc0014180c0, 0x54, 0x0, 0x0, 0x0, 0x0, 0xc0012fdc89, 0x19, ...)
        /go/pkg/mod/github.com/rancher/k3s@v1.22.3-0.20211007194742-737f722315b9/pkg/agent/run.go:212 +0x438
github.com/rancher/k3s/pkg/cli/agent.Run(0xc0019bec60, 0x0, 0x0)
        /go/pkg/mod/github.com/rancher/k3s@v1.22.3-0.20211007194742-737f722315b9/pkg/cli/agent/agent.go:77 +0x3b8
github.com/rancher/rke2/pkg/rke2.Agent(0xc0019bec60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /source/pkg/rke2/rke2.go:117 +0xd3
github.com/rancher/rke2/pkg/cli/cmds.AgentRun(0xc0019bec60, 0x0, 0x0)
        /source/pkg/cli/cmds/agent.go:87 +0xda
github.com/urfave/cli.HandleAction(0x7ff7d3917640, 0x7ff7d4a158c8, 0xc0019bec60, 0xc0019bec60, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x110
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000170e00, 0xc0019beb00, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:410 +0x7e7
github.com/urfave/cli.Command.startApp(0x7ff7d47b24a6, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff7d47d195b, 0xe, 0xc001ac5980, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x81f
github.com/urfave/cli.Command.Run(0x7ff7d47b24a6, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ff7d47d195b, 0xe, 0xc001ac5980, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9d4
github.com/urfave/cli.(*App).Run(0xc000170c40, 0xc00041ba00, 0x7, 0x8, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
        /source/main.go:20 +0x694
```

**Steps To Reproduce:**

- Install as agent node
- Uninstall
- Delete the node from the cluster
- reconfigure files the same way and then run the binary `rke2 agent`

**Expected behavior:**

Should reinstall and join again

**Actual behavior:**

It does not and hits this panic

**Additional context / logs:**

N/A

**Comment by rancher-max** [comment]
### Validated in all of v1.21.11-rc6+rke2r1, v1.22.8-rc6+rke2r1, and v1.23.5-rc5+rke2r1 

- After running uninstall I am able to reuse the nodes and join back into a cluster. The panic is gone. Validated this in both airgap and non airgap setups on Windows 2022 and Windows 2019 servers.

Note that there is still some room for improvement. I saw the following three things happen:
1. In an airgap setup that was running the rke2.exe binary, it looped with this for a while before eventually recovering itself and continuing:
```
PS C:\Users\Administrator> .\rke2-uninstall.ps1
Beginning the uninstall process
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
INFO: Could not find containerd namespaces, will use default list instead:
default cattle-system kube-system fleet-default calico-system
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
ctr: failed to dial "\\\\.\\\\pipe\\\\containerd-containerd": context deadline exceeded
```
2. In one case in a non-airgap setup using rke2 v1.23 on Windows 2022 and running as a service, the `c:\var` directory failed to get cleaned up. It said something about permissions, but I was running as Administrator user so I'm not sure why that occurred.
3. In another airgap case running the rke2 binary, this time on Windows 2019, the calico-node process was not removed and I had to remove it manually. I noticed this because after ctrl+c out of the binary, it kept looping anyway with `felix` logs.

I am going to create a separate issue for these three cases to just cover overall improvements with the uninstall script, but there is nothing blocking anymore and this is generally successful since now we can use the uninstall script to reuse nodes.
