### ISSUE TITLE
[RC BUG] Unable to restore a snapshot on a fresh node 

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2#2287]
**Environmental Info:**
RKE2 Version: 

v1.22.5-rc2+rke2r1, v1.21.8-rc2+rke2r1, v1.20.14-rc2+rke2r1

Node(s) CPU architecture, OS, and Version: 

SLES 15 SP 2

Cluster Configuration:

initially 3 servers 1 agent. All those machines are stopped and I'm trying to restore to a single server

**Describe the bug:**

When trying to restore the snapshot, during the reset, it fails with a panic:
```
INFO[0008] Pulling images from /var/lib/rancher/rke2/agent/images/etcd-image.txt 
INFO[0008] Pulling image index.docker.io/rancher/hardened-etcd:v3.4.13-k3s3-build20211118... 
{"level":"warn","ts":"2021-12-20T19:10:37.816Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
INFO[0011] Failed to test data store connection: context deadline exceeded 
INFO[0014] Imported images from /var/lib/rancher/rke2/agent/images/etcd-image.txt in 5.629238228s 
panic: close of closed channel

goroutine 1 [running]:
github.com/rancher/k3s/pkg/agent.run(0x747a678, 0xc000a9d9c0, 0xc0013ef310, 0x4e, 0x0, 0x0, 0x0, 0x0, 0xc001c131d0, 0x16, ...)
	/go/pkg/mod/github.com/rancher/k3s@v1.21.7-engine0.0.20211217181024-7e79ba7afd1f/pkg/agent/run.go:94 +0x7cd
github.com/rancher/k3s/pkg/agent.Run(0x747a678, 0xc000a9d9c0, 0xc0013ef310, 0x4e, 0x0, 0x0, 0x0, 0x0, 0xc001c131d0, 0x16, ...)
	/go/pkg/mod/github.com/rancher/k3s@v1.21.7-engine0.0.20211217181024-7e79ba7afd1f/pkg/agent/run.go:224 +0x41d
github.com/rancher/k3s/pkg/cli/server.run(0xc000a9a160, 0xa14a440, 0x0, 0x0, 0x0, 0xc0019aeb48, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/k3s@v1.21.7-engine0.0.20211217181024-7e79ba7afd1f/pkg/cli/server/server.go:480 +0x1fd8
github.com/rancher/k3s/pkg/cli/server.RunWithControllers(...)
	/go/pkg/mod/github.com/rancher/k3s@v1.21.7-engine0.0.20211217181024-7e79ba7afd1f/pkg/cli/server/server.go:46
github.com/rancher/rke2/pkg/rke2.Server(0xc000a9a160, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/source/pkg/rke2/rke2.go:113 +0x52b
github.com/rancher/rke2/pkg/cli/cmds.ServerRun(0xc000a9a160, 0x0, 0x0)
	/source/pkg/cli/cmds/server.go:149 +0xb8
github.com/urfave/cli.HandleAction(0x5a5e800, 0x6c18d08, 0xc000a9a160, 0xc000a9a160, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x699f2f4, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x69e6c20, 0x15, 0xc0016e4e58, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc0018f1880, 0xc000070160, 0xb, 0xb, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
	/source/main.go:22 +0xa94
```

**Steps To Reproduce:**

- Install rke2 in HA configuration
- Take a snapshot to s3
- Bring down all nodes
- On a fresh VM, attempt to restore the snapshot: `sudo rke2 server --cluster-reset --etcd-s3 --cluster-reset-restore-path=<name in s3> --etcd-s3-bucket=<bucket name> --etcd-s3-folder=<optional folder> --etcd-s3-region=<region> --etcd-s3-access-key=<key> --etcd-s3-secret-key=<secret> --token=<token value from the original cluster>`

**Expected behavior:**

Snapshot should restore successfully

**Actual behavior:**

Snapshot fails to restore with the stack trace shown

**Additional context / logs:**

**Comment by rancher-max** [comment]
Validated in all of v1.20.14-rc3+rke2r1, v1.21.8-rc3+rke2r1, and v1.22.5-rc3+rke2r1 that following the same steps works correctly.

The cluster restored properly, then I restarted the service. In all cases, the service actually failed to restart, looping with: `level=info msg="runtime is not yet initialized"`. I ran `rke2-killall.sh` and then restarted again and it worked correctly. I was also able to delete the old nodes and use the cluster successfully to deploy new workloads. In deleting the old nodes, I had to remove the finalizers in all cases.

I believe needing to restart the service twice and run killall in between is an issue, but is non-blocking for this release so I will create its own issue for it.
