### ISSUE TITLE
Cluster suddenly broke, cluster reset fails

### ISSUE THREAD

**Issue by pgagarinov** [rancher/rke2#2338]
**Environmental Info:**
RKE2 Version: 

```
rke2 version v1.22.5+rke2r1 (ce3e572376cbb1d8157f46e2ae29d7d7834067f1)
go version go1.16.10b7
```
Node(s) CPU architecture, OS, and Version: 

Rocky Linux 8.5, Intel.
```
4.18.0-348.7.1.el8_5.x86_64
```
Cluster Configuration:

3 server nodes, resetting the third one.

**Describe the bug:**

The cluster suddenly stopped responding, presumably after changing the hostname of the first node from `rk-rocky-r0.localdomain` to `rk-rocky-r0`. Cluster continued to function for a few minutes after t he change and then stopped responding.
An attempt to reset the third node failed,

`rke2 server --cluster reset` g

generates the following logs
```
E0110 22:37:25.703950  144351 kubelet.go:1343] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
```

then
```
E0110 22:37:25.994278  144351 container_manager_linux.go:549] "Failed to find cgroups of kubelet" err="cpu and memory cgroup hierarchy not unified.  cpu: /, memory: /user.slice/user-1000.slice/session-1.scope"
I0110 22:37:25.997051  144351 manager.go:609] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
```
then
```
E0110 22:37:28.271059  144351 remote_runtime.go:296] "RemoveContainer from runtime service failed" err="rpc error: code = Unknown desc = failed to set removing state for container \"90faeda21373853cfb320c72df3bf633f39be253256654c7a12cced3ebba1694\": container is already in removing state" containerID="90faeda21373853cfb320c72df3bf633f39be253256654c7a12cced3ebba1694"
```

then 
```
E0110 22:37:28.996969  144351 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 259 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x44e4e20, 0x7552530)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x44e4e20, 0x7552530)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateDevicePath(0xc0002998c0, 0xc000a83c88)
	/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:599 +0x41
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateStates(0xc0002998c0, 0xc000a83c88, 0xc00138a900, 0x52)
	/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:630 +0x50
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).syncStates(0xc0002998c0)
	/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:434 +0x3d7
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).sync(0xc0002998c0)
	/go/src/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:348 +0x4e
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.fun
```

and finally

```
panic: unexpected removal of unknown remote peer

goroutine 339 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00602c540, 0xc006213640, 0x1, 0x1)
	/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*Logger).Panic(0xc00120a500, 0x6ce8dbe, 0x29, 0xc006213640, 0x1, 0x1)
	/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:227 +0x85
go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).removePeer(0xc00011c540, 0x36fd48ae8fde44e6)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/api/rafthttp/transport.go:346 +0x58c
go.etcd.io/etcd/server/v3/etcdserver/api/rafthttp.(*Transport).RemovePeer(0xc00011c540, 0x36fd48ae8fde44e6)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/api/rafthttp/transport.go:329 +0x7d
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyConfChange(0xc001115100, 0x1, 0x36fd48ae8fde44e6, 0x0, 0x0, 0x0, 0x44e67e412dbc6ea9, 0xc000766000, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/server.go:2303 +0x872
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).apply(0xc001115100, 0xc0052e5600, 0x341, 0x4e0, 0xc000766000, 0xc005e2ca78, 0xc005e2ca30, 0x237ea1d)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/server.go:2135 +0x59a
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyEntries(0xc001115100, 0xc000766000, 0xc005e32fd0)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/server.go:1357 +0xe5
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).applyAll(0xc001115100, 0xc000766000, 0xc005e32fd0)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/server.go:1179 +0x88
go.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).run.func8(0x7728ef8, 0xc003f90040)
	/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.0-k3s2/etcdserver/server.go:1111 +0x3c
go.etcd.io/etcd/pkg/v3/schedule.(*fifo).run(0xc000496420)
	/go/pkg/mod/go.etcd.io/etcd/pkg/v3@v3.5.0/schedule/schedule.go:157 +0xf3
created by go.etcd.io/etcd/pkg/v3/schedule.NewFIFOScheduler
	/go/pkg/mod/go.etcd.io/etcd/pkg/v3@v3.5.0/schedule/schedule.go:70 +0x13b

```

**Expected behavior:**

I expected the cluster restore to be successful.

**Actual behavior:**

**Additional context / logs:**

Here is the full log: [output.log](https://github.com/rancher/rke2/files/7841561/out2.log)

**Comment by brandond** [comment]
Can you attach the complete rke2-server log, as well as the output of the cluster-reset command? While the bits you included are interesting, there's not always enough to indicate the full story as to what's causing the crash.

I suspect this may be related to https://github.com/k3s-io/k3s/issues/4870

**Comment by pgagarinov** [comment]
Output of rke server --reset-cluster: [https://github.com/rancher/rke2/files/7841561/out2.log]

Output of rke2-server log:
