### ISSUE TITLE
rke2 secrets-encrypt status not working: invalid annotation

### ISSUE THREAD

**Issue by bovy89** [rancher/rke2#2486]
**Environmental Info:**
RKE2 Version: 
rke2 version v1.22.6+rke2r1 (2dcedaf55c49ef9b24849c92702bdc12ea589d7a)
go version go1.16.10b7

Node(s) CPU architecture, OS, and Version: 
AlmaLinux release 8.5 (Arctic Sphynx)
4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 14:35:04 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
1 server

**Describe the bug:**

```
# rke2 secrets-encrypt status
FATA[0000] https://127.0.0.1:9345/v1-rke2/encrypt/status: 500 Internal Server Error

# k get node --show-labels
NAME                  STATUS   ROLES                       AGE     VERSION          LABELS
rke-m01.example.com   Ready    control-plane,etcd,master   3d10h   v1.22.6+rke2r1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=rke2,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=rke-m01.example.com,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/etcd=true,node-role.kubernetes.io/master=true,node.kubernetes.io/instance-type=rke2

journalctl -u rke2-server.service
time="2022-02-15T20:36:14Z" level=warning msg="secrets-encrypt-60217: invalid annotation  found on node rke-m01.example.com"
```

**Comment by brandond** [comment]
@dereknola any ideas?

**Comment by dereknola** [comment]
@bovy89 Can you print out the following? It looks like something went wrong with the annotation.
```
kubectl get node rke-m01.example.com -o jsonpath="{.metadata.annotations.rke2\.io/encryption-config-hash}"
```

**Comment by bovy89** [comment]
empty result

**Comment by dereknola** [comment]
Ah okay, that explains it, there isn't an existing annotation, which is causing issues. I will work on a proper fix, but for now you should be able to work around that by doing the following:
```
# Make sure this gives you an output
cat /var/lib/rancher/rke2/server/cred/encryption-state.json 
# Create the needed annotation manually
kubectl annotate no rke-m01.example.com rke2.io/encryption-config-hash=$(cat /var/lib/rancher/rke2/server/cred/encryption-state.json) --overwrite
```

**Comment by bovy89** [comment]
That file does not exists.

On a fresh 1.22 installation `/var/lib/rancher/rke2/server/cred/encryption-state.json` exists, annotation is present and  `rke2 secrets-encrypt status` works

**Comment by bovy89** [comment]
It works ;) Thanks

**Comment by dereknola** [comment]
For QA info:
To verify this fix (and its backports):
#### Verification ####
- Install pre encryptions rotation version of RKE2: v1.22.4+k3s1
- Start RKE2
- Stop RKE2
- Upgrade to latest branch commit (all relevant branches have the fix)
- Start RKE2
- Run `rke2 secrets-encrypt status` and note that it does not fail with 500 Internal Server Error

**Comment by VestigeJ** [comment]
Hey @dereknola - I know it's EOD but for tomorrow when you have time could you advise on testing the secrets encrypt fix you've added to test. 

I've walked through your steps for validation but the below output is what the latest commit branches are generating as output. 
v1.21 COMMIT=ff037827d0df3a725a4dfd0d5748679c1e5ee0b1
v1.22 COMMIT=90d94ddbd8601c4b1bc15460811239e1c99ba1b3
v1.23 COMMIT=8c8bbf1e5f987c45c4f584fedbf6606c4967e0a9


$ rke2 secrets-encrypt status
```
status flag redefined: server
panic: status flag redefined: server

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc001971800, {0x70226b8, 0xa78b220}, {0x651fda3, 0x6}, {0x65b9747, 0x20})
        /usr/local/go/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:762
github.com/urfave/cli.StringFlag.ApplyWithError.func1({0x651fda3, 0x6})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag_string.go:64 +0x6c
github.com/urfave/cli.eachName({0x651fda3, 0x0}, 0xc002e9e278)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag.go:130 +0x93
github.com/urfave/cli.StringFlag.ApplyWithError({{0x651fda3, 0x8}, {0x65b9747, 0x20}, {0xc002ae7610, 0x8}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag_string.go:62 +0xe9
github.com/urfave/cli.flagSet({0x651856b, 0x6}, {0xc001951c20, 0x5, 0xa78b3c0})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag.go:115 +0x163
github.com/urfave/cli.(*Command).newFlagSet(...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:214
github.com/urfave/cli.(*Command).parseFlags(0xc001670140, {0xa7c37f8, 0xc001951c20, 0x4}, 0x6)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:195 +0xb9
github.com/urfave/cli.Command.Run({{0x651856b, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6610e4f, 0x2a}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:117 +0x22a
github.com/urfave/cli.(*App).RunAsSubcommand(0xc002148c40, 0xc00216f760)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0x653ef64, 0xf}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6620cd6, 0x2c}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0x653ef64, 0xf}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6620cd6, 0x2c}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc002148a80, {0xc000116900, 0x3, 0x3})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
        /source/main.go:22 +0xaf2
```

$ history
```
    1  VERSION=v1.23.1+rke2r1
    2  curl https://get.rke2.io | sudo INSTALL_RKE2_VERSION=$VERSION INSTALL_RKE2_TYPE=server sh -
    3  sudo chmod 644 /etc/rancher/rke2/rke2.yaml 
    4  sudo systemctl enable rke2-server
    5  sudo systemctl start rke2-server
    6  sudo chmod 644 /etc/rancher/rke2/rke2.yaml &&  PATH=$PATH:/var/lib/rancher/rke2/bin && export KUBECONFIG=/etc/rancher/rke2/rke2.yaml 
    7  kubectl get nodes
    8  COMMIT=8c8bbf1e5f987c45c4f584fedbf6606c4967e0a9
    9  rke2 -v
   10  sudo systemctl stop rke2-server
   11  curl https://get.rke2.io | sudo INSTALL_RKE2_COMMIT=$COMMIT INSTALL_RKE2_TYPE=server sh -
   12  sudo systemctl start rke2-server
   13  rke2 secrets-encrypt status
```

**Comment by dereknola** [comment]
New issue https://github.com/rancher/rke2/issues/2486 to track error

**Comment by VestigeJ** [comment]
Closing due to valid tests listed below for each branch

[v1.23](https://github.com/rancher/rke2/issues/2539)  
[v1.22](https://github.com/rancher/rke2/issues/2546) 
[v1.21](https://github.com/rancher/rke2/issues/2545)

**Comment by VestigeJ** [comment]
**Validated but this branch has always had the feature moved from  v1.23.1+rke2r1 to v1.23.4+rke2r1 **

$ rke2 -v
```
rke2 version v1.23.1+rke2r1 (721007d1e9cedbf12185677e719806e2a0118335)
go version go1.17.5b7
```
$ kubectl get nodes
```
NAME               STATUS   ROLES                       AGE     VERSION
ip-72-31-5-5   Ready    control-plane,etcd,master   3m53s   v1.23.1+rke2r1
```
$ sudo rke2 secrets-encrypt status
```
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```

$ sudo systemctl stop rke2-server
$ sudo rke2-killall.sh
$ COMMIT=2e41989b2cb678b07b7cc91f55defac60c7b8f24
$ curl https://get.rke2.io/ | sudo INSTALL_RKE2_COMMIT=$COMMIT INSTALL_RKE2_TYPE="server --secrets-encrypt" sh -
$ sudo systemctl start rke2-server
$ sudo chmod 644 /etc/rancher/rke2/rke2.yaml

$ kubectl get nodes
```
NAME               STATUS   ROLES                       AGE   VERSION
ip-72-31-5-5   Ready    control-plane,etcd,master   31m   v1.23.4+rke2r1
```
$ sudo rke2 secrets-encrypt status
```
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```
