### ISSUE TITLE
`rke2 secrets-encrypt status` Fails

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#2539]
**Environmental Info:**
RKE2 Version: 

Latest commits on all branches

Cluster Configuration:

1 Server
**Describe the bug:**

```
$ rke2 secrets-encrypt status

status flag redefined: server
panic: status flag redefined: server

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc001971800, {0x70226b8, 0xa78b220}, {0x651fda3, 0x6}, {0x65b9747, 0x20})
        /usr/local/go/src/flag/flag.go:879 +0x2f4
flag.(*FlagSet).StringVar(...)
        /usr/local/go/src/flag/flag.go:762
github.com/urfave/cli.StringFlag.ApplyWithError.func1({0x651fda3, 0x6})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag_string.go:64 +0x6c
github.com/urfave/cli.eachName({0x651fda3, 0x0}, 0xc002e9e278)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag.go:130 +0x93
github.com/urfave/cli.StringFlag.ApplyWithError({{0x651fda3, 0x8}, {0x65b9747, 0x20}, {0xc002ae7610, 0x8}, {0x0, 0x0}, 0x0, 0x0, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag_string.go:62 +0xe9
github.com/urfave/cli.flagSet({0x651856b, 0x6}, {0xc001951c20, 0x5, 0xa78b3c0})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/flag.go:115 +0x163
github.com/urfave/cli.(*Command).newFlagSet(...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:214
github.com/urfave/cli.(*Command).parseFlags(0xc001670140, {0xa7c37f8, 0xc001951c20, 0x4}, 0x6)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:195 +0xb9
github.com/urfave/cli.Command.Run({{0x651856b, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6610e4f, 0x2a}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:117 +0x22a
github.com/urfave/cli.(*App).RunAsSubcommand(0xc002148c40, 0xc00216f760)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x9ec
github.com/urfave/cli.Command.startApp({{0x653ef64, 0xf}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6620cd6, 0x2c}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x6e9
github.com/urfave/cli.Command.Run({{0x653ef64, 0xf}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x6620cd6, 0x2c}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x808
github.com/urfave/cli.(*App).Run(0xc002148a80, {0xc000116900, 0x3, 0x3})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
        /source/main.go:22 +0xaf2
```
**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**

Command does not fail
**Actual behavior:**

Failure on any `secret-encrypt` command
**Additional context / logs:**

Pulling in this K3s PR https://github.com/k3s-io/k3s/pull/5016 brought duplicate server flags for the `secrets-encrypt` command.

**Comment by VestigeJ** [comment]
**Validated on COMMIT=2e41989b2cb678b07b7cc91f55defac60c7b8f24**

$ rke2 -v
```
rke2 version v1.23.4-dev+2e41989b (2e41989b2cb678b07b7cc91f55defac60c7b8f24)
go version go1.17.5b7
```

$ kubectl get nodes
```
NAME               STATUS   ROLES                       AGE    VERSION
ip-2-3-8-254   Ready    control-plane,etcd,master   12m    v1.23.4+rke2r1
ip-2-3-8-190   Ready    <none>                      12m    v1.23.4+rke2r1
ip-2-3-8-145   Ready    control-plane,etcd,master   19m    v1.23.4+rke2r1
ip-2-3-8-225   Ready    control-plane,etcd,master   8m1s   v1.23.4+rke2r1
```

$ sudo rke2 secrets-encrypt status
```
Encryption Status: Enabled
Current Rotation Stage: start
Server Encryption Hashes: All hashes match

Active  Key Type  Name
------  --------  ----
 *      AES-CBC   aescbckey
```
