### ISSUE TITLE
beta12 results in an immediate panic

### ISSUE THREAD

**Issue by joshrwolf** [rancher/rke2#264]
Getting the following on any and all executions of the `rke2` cli:

```
[root@ip-10-0-101-133 centos]# /usr/bin/rke2 server
panic: new unknown option from k3s etcd-disable-snapshots, new unknown option from k3s etcd-snapshot-schedule-cron, new unknown option from k3s etcd-snapshot-retention, new unknown option from k3s etcd-snapshot-dir, new unknown option from k3s cluster-reset-restore-path

goroutine 1 [running]:
github.com/rancher/rke2/pkg/cli/cmds.mustCmdFromK3S(0xc000a926c0, 0xc000ba66f0, 0x5a89138)
	/source/pkg/cli/cmds/k3sopts.go:36 +0x6f
github.com/rancher/rke2/pkg/cli/cmds.init()
	/source/pkg/cli/cmds/server.go:15 +0x20b7
```

**Comment by briandowns** [comment]
Worked on in #265

**Comment by briandowns** [comment]
PR has been merged. Please let me know if this can be closed.

**Comment by joshrwolf** [comment]
Can confirm #265 fixed this, thanks!
