### ISSUE TITLE
Static build of kubelet crashes with signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#333]
The change to static builds in rancher/rke2#332 results in kubelet segfaulting. Unfortunately because we don't capture kubelet stderr, all that rke2 reports is `ERRO[1199] Kubelet exited: exit status 2`. Rebuilding rke2 with stderr capture enabled shows a nice segfault:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7ff71c04a5ed]

runtime stack:
runtime.throw(0x43bae6b, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 306 [syscall]:
runtime.cgocall(0x329a4c0, 0xc0005b25c0, 0xc000b7cad0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0005b2590 sp=0xc0005b2558 pc=0x40638b
net._C2func_getaddrinfo(0xc000e800e0, 0x0, 0xc0008d35f0, 0xc000b7cad0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:92 +0x55 fp=0xc0005b25c0 sp=0xc0005b2590 pc=0x566145
net.cgoLookupIPCNAME.func1(0xc000e800e0, 0x13, 0x13, 0xc0008d35f0, 0xc000b7cad0, 0x2, 0xc0005b26a0, 0x569522)
	/usr/local/go/src/net/cgo_unix.go:161 +0xd2 fp=0xc0005b2608 sp=0xc0005b25c0 pc=0x56bba2
net.cgoLookupIPCNAME(0x4315f41, 0x2, 0x7ffc347ed536, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x183 fp=0xc0005b2718 sp=0xc0005b2608 pc=0x5675d3
net.cgoIPLookup(0xc0007fcae0, 0x4315f41, 0x2, 0x7ffc347ed536, 0x12)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0005b27b8 sp=0xc0005b2718 pc=0x567d07
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0005b27c0 sp=0xc0005b27b8 pc=0x46a991
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7
```

Apparently this is a fairly well-known issue caused by statically linking without using the `netgo` tag. k3s is using netgo, and is also statically linked, so we should probably do the same in rke2.

**Comment by davidnuzik** [comment]
@briandowns @cjellick advice on what QA should be checking here?

**Comment by brandond** [comment]
Just look for rke2 running successfully?  With this issue it would get stuck in a loop trying to start the kubelet and failing repeatedly with `ERRO[1199] Kubelet exited: exit status 2`

**Comment by cjellick** [comment]
It probably makes sense to wait until @dweomer's static build overhaul represented by this issue:
https://github.com/rancher/rke2/issues/335
is complete and assigned over to QA.

**Comment by rancher-max** [comment]
#### Validated using `v1.18.9-beta21+rke2`

- Can show the fix for this easily using nodes in AWS without an IAM role, and setting the flag `cloud-provider-name: aws`. Previously, this gave repeated errors of `Kubelet exited: exit status 2`. Now this is much nicer, showing:
```
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: F0928 17:52:52.956256    2291 server.go:274] failed to run Kubelet: could not init cloud provider "aws": error finding instance i-0c2159960e87f50b1: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: goroutine 1 [running]:
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/klog.stacks(0xc00034b200, 0xc000982000, 0x140, 0x1b6)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/klog.go:875 +0xb8
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/klog.(*loggingT).output(0x6e75540, 0xc000000003, 0xc0006100e0, 0x6cf164e, 0x9, 0x112, 0x0)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/klog.go:826 +0x330
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/klog.(*loggingT).printDepth(0x6e75540, 0xc000000003, 0x1, 0xc000873c30, 0x1, 0x1)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/klog.go:698 +0x129
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/klog.(*loggingT).print(...)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/klog.go:689
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/klog.Fatal(...)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/klog/klog.go:1256
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0002fef00, 0xc00004e250, 0x21, 0x23)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/cmd/kubelet/app/server.go:274 +0x622
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: github.com/spf13/cobra.(*Command).execute(0xc0002fef00, 0xc00004e250, 0x21, 0x23, 0xc0002fef00, 0xc00004e250)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fef00, 0x16390407678ac02d, 0x6e74f00, 0xc000000180)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: github.com/spf13/cobra.(*Command).Execute(...)
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         /go/src/github.com/kubernetes/kubernetes/vendor/github.com/spf13/cobra/command.go:864
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]: main.main()
Sep 28 17:52:52 ip-172-31-37-153 rke2[2291]:         cmd/kubelet/kubelet.go:41 +0xcd
Sep 28 17:52:52 ip-172-31-37-153 rke2[2182]: time="2020-09-28T17:52:52Z" level=error msg="Kubelet exited: exit status 255"
```
- This also doesn't appear to break anything else. I'm not seeing any regressions when the kubelet builds and runs successfully.
