### ISSUE TITLE
stopping and starting a server node causes a panic while joining a cluster

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rke2#392]
steps to reproduce:

- start 2 rke2 server nodes
- start third node
- interrupt the process right after etcd starts
- try to start rke2 again on this node

results:

a panic happens:

```
INFO[0000] To join node to cluster: rke2 agent -s https://172.17.0.4:9345 -t ${NODE_TOKEN} 
INFO[0000] Waiting for API server to become available   
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1313e39]
goroutine 274 [running]:
github.com/rancher/k3s/pkg/clientaccess.Get(0x5eae359, 0x8, 0x0, 0x6ca6320, 0xc000244780, 0xc0011d41c0, 0x20, 0xc0011241b0)
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/clientaccess/token.go:179 +0x29
github.com/rancher/k3s/pkg/etcd.(*ETCD).clientURLs(0xc001504940, 0x6ca6320, 0xc0002446c0, 0x0, 0x0, 0xffffffffffffffff, 0xc001769ca0, 0x16d518a, 0xc001310000, 0x0, ...)
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/etcd/etcd.go:547 +0x72
github.com/rancher/k3s/pkg/etcd.(*ETCD).promoteMember(0xc001504940, 0x6ca6320, 0xc0002446c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/etcd/etcd.go:509 +0x75
github.com/rancher/k3s/pkg/etcd.(*ETCD).Test(0xc001504940, 0x6ca6320, 0xc0002446c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/etcd/etcd.go:83 +0x714
github.com/rancher/k3s/pkg/cluster.(*Cluster).testClusterDB.func1(0xc00114ed80, 0xc0008b4aa0, 0x6ca62a0, 0xc0008d3240)
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/cluster/managed.go:33 +0xa2
created by github.com/rancher/k3s/pkg/cluster.(*Cluster).testClusterDB
	/go/pkg/mod/github.com/galal-hussein/k3s@v0.1.1-0.20200929175116-1fd4c6b83a4d/pkg/cluster/managed.go:30 +0x8
```

**Comment by brandond** [comment]
This is occurring because we consider etcd to be initialized as soon as the WAL dir exists. If you kill RKE2 before it promotes itself from learner, it will try to do so again on startup - but we've skipped storing clientAccessInfo.

I've put in a PR with a minimal fix, but long-term I think we need to have a dedicated goroutine that handles etcd housekeeping, including promotion. This would free the joining node from the responsibility of promoting itself.

**Comment by davidnuzik** [comment]
Assigned to @MonzElmasry for QA check.

**Comment by MonzElmasry** [comment]
Validated via the instructions given, Started 2 rke2 servers, interrupted the third right after etcd started 
```
INFO[0043] etcd data store connection OK                
INFO[0043] Waiting for API server to become available   
^CWARN[0046] Unable to watch for tunnel endpoints: Get https://127.0.0.1:6443/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&resourceVersion=0&watch=true: context canceled 
INFO[0046] Proxy done                                    err="context canceled" url="wss://127.0.0.1:9345/v1-rke2/connect"
FATA[0046] server stopped: http: Server closed          
```

then started rke2 server on the 3rd master 
```
NAME                    STATUS   ROLES         AGE     VERSION
node/ip-172-31-16-61    Ready    etcd,master   7m29s   v1.18.9-beta22+rke2
node/ip-172-31-29-16    Ready    etcd,master   17m     v1.18.9-beta22+rke2
node/ip-172-31-29-167   Ready    etcd,master   3m35s   v1.18.9-beta22+rke2
```

working as expected @davidnuzik
