### ISSUE TITLE
The restart rke2-server faild

### ISSUE THREAD

**Issue by yingyue520** [rancher/rke2#5094]
**Environmental Info:**
RKE2 Version: rke2 v1.26.10+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux rke2-m1 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
```yaml
token: K106f8862180fd5b0e8904a46833e6b83d12661b1767e7e239748d1f2b7bf498371::server:694191e4eb3c32b5f26c496bbd479308
system-default-registry: "registry.cn-hangzhou.aliyuncs.com"
tls-san: 192.168.229.200
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
node-label:
  - "node=Master"
```

**Describe the bug:**
I tried to restart rke2-server, but couldn't do it anyway.
Honey, excuse me. I need some help.

**Additional context / logs:**
```console 
[root@rke2-m1 ~]# systemctl restart rke2-server
Job for rke2-server.service failed because the control process exited with error code. See "systemctl status rke2-server.service" and "journalctl -xe" for details.
[root@rke2-m1 ~]# journalctl -xe
12月 03 21:49:18 rke2-m1 sh[24774]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
12月 03 21:49:18 rke2-m1 sh[24774]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
12月 03 21:49:18 rke2-m1 rke2[24783]: time="2023-12-03T21:49:18+08:00" level=warning msg="not running in CIS mode"
12月 03 21:49:18 rke2-m1 rke2[24783]: time="2023-12-03T21:49:18+08:00" level=info msg="Applying Pod Security Admission Configuration"
12月 03 21:49:18 rke2-m1 rke2[24783]: time="2023-12-03T21:49:18+08:00" level=info msg="Starting rke2 v1.26.10+rke2r2 (21e3a8c82da71473f2b846065dcab197a9b2c9d8)"
12月 03 21:49:18 rke2-m1 rke2[24783]: time="2023-12-03T21:49:18+08:00" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
12月 03 21:49:18 rke2-m1 rke2[24783]: time="2023-12-03T21:49:18+08:00" level=info msg="Starting temporary etcd to reconcile with datastore"
12月 03 21:49:18 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:18.832637+0800","caller":"embed/etcd.go:127","msg":"configuring peer listeners","listen-peer-urls":["http://127.0.0.1:2400"]}
12月 03 21:49:18 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:18.832739+0800","caller":"embed/etcd.go:135","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2399"]}
12月 03 21:49:18 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:18.833072+0800","caller":"embed/etcd.go:309","msg":"starting an etcd server","etcd-version":"3.5.9","git-sha":"Not provided (use ./build instead 
12月 03 21:49:18 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:18.838953+0800","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/rancher/rke2/server/db/etcd-tmp/member/snap/db","t
12月 03 21:49:18 rke2-m1 rke2[24783]: {"level":"warn","ts":"2023-12-03T21:49:18.839086+0800","caller":"wal/util.go:90","msg":"ignored file in WAL directory","path":"0000000000000005-0000000000057930.wal.broken"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.281413+0800","caller":"etcdserver/server.go:509","msg":"recovered v2 store from snapshot","snapshot-index":1220122,"snapshot-size":"11 kB"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.281463+0800","caller":"etcdserver/server.go:522","msg":"recovered v3 backend from snapshot","backend-size-bytes":24879104,"backend-size":"25 M
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"warn","ts":"2023-12-03T21:49:19.281501+0800","caller":"wal/util.go:90","msg":"ignored file in WAL directory","path":"0000000000000005-0000000000057930.wal.broken"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.3496+0800","caller":"etcdserver/raft.go:603","msg":"forcing restart member","cluster-id":"17705f0d6307e48","local-member-id":"9b94aa8de130cb6d
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.349829+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"9b94aa8de130cb6d switched to configuration voters=(112107728987771892
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.349861+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"9b94aa8de130cb6d became follower at term 13"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.349872+0800","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"newRaft 9b94aa8de130cb6d [peers: [9b94aa8de130cb6d], term: 13, commit
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.349991+0800","caller":"api/capability.go:75","msg":"enabled capabilities for version","cluster-version":"3.5"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.350006+0800","caller":"membership/cluster.go:278","msg":"recovered/added member from store","cluster-id":"17705f0d6307e48","local-member-id":"
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.350017+0800","caller":"membership/cluster.go:287","msg":"set cluster version from store","cluster-version":"3.5"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"warn","ts":"2023-12-03T21:49:19.350369+0800","caller":"auth/store.go:1238","msg":"simple token is not cryptographically signed"}
12月 03 21:49:19 rke2-m1 rke2[24783]: {"level":"info","ts":"2023-12-03T21:49:19.350564+0800","caller":"mvcc/kvstore.go:323","msg":"restored last compact revision","meta-bucket-name":"meta","meta-bucket-name-key":"finishedC
12月 03 21:49:19 rke2-m1 rke2[24783]: panic: runtime error: slice bounds out of range [:8] with capacity 5
12月 03 21:49:19 rke2-m1 rke2[24783]: goroutine 223 [running]:
12月 03 21:49:19 rke2-m1 rke2[24783]: go.etcd.io/etcd/server/v3/mvcc.bytesToRev(...)
12月 03 21:49:19 rke2-m1 rke2[24783]: /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/revision.go:58
12月 03 21:49:19 rke2-m1 rke2[24783]: go.etcd.io/etcd/server/v3/mvcc.restoreIntoIndex.func1()
12月 03 21:49:19 rke2-m1 rke2[24783]: /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/kvstore.go:444 +0x6fc
12月 03 21:49:19 rke2-m1 rke2[24783]: created by go.etcd.io/etcd/server/v3/mvcc.restoreIntoIndex
12月 03 21:49:19 rke2-m1 rke2[24783]: /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/kvstore.go:419 +0xfa
12月 03 21:49:19 rke2-m1 systemd[1]: rke2-server.service: main process exited, code=exited, status=2/INVALIDARGUMENT
12月 03 21:49:19 rke2-m1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
-- Subject: Unit rke2-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit rke2-server.service has failed.
-- 
-- The result is failed.
12月 03 21:49:19 rke2-m1 systemd[1]: Unit rke2-server.service entered failed state.
12月 03 21:49:19 rke2-m1 systemd[1]: rke2-server.service failed.
```

**Comment by yingyue520** [comment]
I will provide log files 。
I found it prompting me.
        panic: runtime error: slice bounds out of range [:8] with capacity 5
[rke2.log](https://github.com/rancher/rke2/files/13539185/rke2.log)

**Comment by brandond** [comment]
Your etcd database files are corrupt. Did you perform an unsafe reboot or power off of your node? You will need to restore from an etcd snapshot or rejoin the server to the cluster if you have other servers that are still operational.
