### ISSUE TITLE
[BUG] Upgrade from 2.8.3 -> 2.9.2 failed on one of the nodes

### ISSUE THREAD

**Issue by johnwc** [rancher/rke2#7263]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Installation option (Docker install/Helm Chart): Helm, RKE2
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.28
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin
  - If custom, define the set of permissions:

**Describe the bug**
I upgraded our rancher from 2.8.3 to 2.9.2, and one of our nodes failed to reconnect. Looks like something with etcd failing.

```
2024-10-09T06:25:57.632642878Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632028Z","caller":"embed/etcd.go:569","msg":"cmux::serve","address":"10.100.0.14:2380"}
2024-10-09T06:25:57.632669939Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632203Z","caller":"embed/etcd.go:277","msg":"now serving peer/client/metrics","local-member-id":"4af4833621d97d24","initial-advertise-peer-urls":["$
2024-10-09T06:25:57.63268356Z stderr F {"level":"info","ts":"2024-10-09T06:25:57.632238Z","caller":"embed/etcd.go:857","msg":"serving metrics","address":"http://127.0.0.1:2381/"}
2024-10-09T06:25:57.632687889Z stderr F {"level":"panic","ts":"2024-10-09T06:25:57.632475Z","logger":"raft","caller":"etcdserver/zap_raft.go:101","msg":"tocommit(65450530) is out of range [lastIndex(65448169)]. Was the raft log c$
2024-10-09T06:25:57.635864491Z stderr F panic: tocommit(65450530) is out of range [lastIndex(65448169)]. Was the raft log corrupted, truncated, or lost?
2024-10-09T06:25:57.635880604Z stderr F
2024-10-09T06:25:57.635886086Z stderr F goroutine 118 [running]:
2024-10-09T06:25:57.635891052Z stderr F go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000cac000, {0x0, 0x0, 0x0})
2024-10-09T06:25:57.635895772Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
2024-10-09T06:25:57.635906908Z stderr F go.uber.org/zap.(*SugaredLogger).log(0xc000014018, 0x4, {0x134b66d?, 0x40d8a5?}, {0xc000ca8220?, 0x112d2c0?, 0x48223a2264656900?}, {0x0, 0x0, 0x0})
2024-10-09T06:25:57.635911388Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/sugar.go:227 +0xee
2024-10-09T06:25:57.635915704Z stderr F go.uber.org/zap.(*SugaredLogger).Panicf(...)
2024-10-09T06:25:57.635919015Z stderr F         /go/pkg/mod/go.uber.org/zap@v1.17.0/sugar.go:159
2024-10-09T06:25:57.635928024Z stderr F go.etcd.io/etcd/server/v3/etcdserver.(*zapRaftLogger).Panicf(0x3e6a8e9?, {0x134b66d?, 0x4e39415973493175?}, {0xc000ca8220?, 0x59526968634a4d58?, 0x706b495252316b35?})
2024-10-09T06:25:57.635932122Z stderr F         /go/src/go.etcd.io/etcd/server/etcdserver/zap_raft.go:101 +0x49
2024-10-09T06:25:57.635939582Z stderr F go.etcd.io/etcd/raft/v3.(*raftLog).commitTo(0xc000452000, 0x3e6b222)
2024-10-09T06:25:57.635943353Z stderr F         /go/src/go.etcd.io/etcd/raft/log.go:237 +0x103
2024-10-09T06:25:57.635981398Z stderr F go.etcd.io/etcd/raft/v3.(*raft).handleHeartbeat(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.635993251Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:1508 +0x45
2024-10-09T06:25:57.636026089Z stderr F go.etcd.io/etcd/raft/v3.stepFollower(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.636045032Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:1434 +0x3d8
2024-10-09T06:25:57.636049463Z stderr F go.etcd.io/etcd/raft/v3.(*raft).Step(_, {0x8, 0x4af4833621d97d24, 0x707d9c9d046e008a, 0x80, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
2024-10-09T06:25:57.636052732Z stderr F         /go/src/go.etcd.io/etcd/raft/raft.go:975 +0x1335
2024-10-09T06:25:57.636078716Z stderr F go.etcd.io/etcd/raft/v3.(*node).run(0xc0004fe180)
2024-10-09T06:25:57.636197123Z stderr F         /go/src/go.etcd.io/etcd/raft/node.go:356 +0x925
2024-10-09T06:25:57.636219643Z stderr F created by go.etcd.io/etcd/raft/v3.RestartNode
2024-10-09T06:25:57.636254832Z stderr F         /go/src/go.etcd.io/etcd/raft/node.go:244 +0x24a
```

**Comment by johnwc** [comment]
This is by all means related to Rancher, this occurred right after an upgrade. The node never came back online. And your assuming things is wrong, there was no reboot or loss of power. This has actually occurred a few times that I have witnessed with other clients.

Please do not close an issue because you 'feel' like it doesn't belong.

**Comment by johnwc** [comment]
> > The node never came back online.
> 
> Never came back online from what? Why did it go offline in the first place?

The etcd failed... So, it never came back up after the rke2 upgrade. From my memory, the rke2 upgrade restarted the local k8s. Did it happen to upgrade the k8s version going between 2.8.3 to 2.9.2?

> You said that this is the local cluster - a standalone RKE2 cluster that Rancher itself is deployed to, not a cluster managed by Rancher. Is that correct?

Correct

> 
> Upgrading Rancher will not corrupt your etcd database. It won't even cause an upgrade or restart of any RKE2 components. As far as RKE2 is concerned, Rancher is just another workload deployed to the cluster.

Guess what? It did... All we did was run the helm upgrade.

> 
> Check the rke2-server logs in journald to see what happened following the Rancher upgrade. If you have monitoring data available for the time period in question, you might also look at that to gauge system CPU and disk IO following the upgrade. It is possible that there is some underlying issue with node performance not being sufficient to support peak load, and the Rancher upgrade put additional load on the datastore that caused things to fall over.

I can no longer go back that far to check the logs, as the logs for 3 weeks ago have already rolled over. There was no extra load on any server or host. Why would etcd corrupt because of server IO load? It may get behind in transactions and not be able to respond, but data corruption? If that was the case, wouldn't it be a horrible choice for storing things for HA purposes?

**Comment by johnwc** [comment]
> The easiest way to fix this is to stop rke2 with the killall script, delete the etcd datastore files from disk, ensure that the `server` address in the RKE2 config points at an existing server node, and then start RKE2 again to rejoin the cluster.

So, to be clear. We need to do the following on the corrupt node.

1. Run `/bin/rke2-killall.sh`
2. Verify `/etc/rancher/rke2/config.yaml`
3. Delete `/var/lib/rancher/rke2/server/db/etcd` (Directory or just its contents?)
4. Run `systemctl start rke2-server`

**Comment by brandond** [comment]
> The rke2 upgrade restarted the local k8s.

You didn't say that you upgraded RKE2, you said that you upgraded Rancher. Which did you do? Upgrading Rancher will not change anything about the local cluster, it will not upgrade RKE2 or restart any of its components. 

> There was no extra load on any server or host. Why would etcd corrupt because of server IO load?
> I can no longer go back that far to check the logs, as the logs for 3 weeks ago have already rolled over.

If you don't have logs or perf data, how can you say there was no extra load? Upgrading Rancher *will* cause a spike in load as all the components are restarted and trigger updates to reconcile configurations for the new version. These operations put load on the apiserver and datastore.

In general things soldier on but if performance is sufficiently bad the apiserver and/or etcd may time out on IO operations and crash/restart. This shouldn't cause any data loss since etcd writes are guaranteed to be flushed to disk, but this assumes that the underlying OS (and VM if you're not running on bare metal) actually do the right thing when `fsync` is called.

Without logs it's not really possible to reconstruct the actual sequence of events though.

> We need to do the following on the corrupt node.

Correct. Entire directory.

**Comment by johnwc** [comment]
> > The rke2 upgrade restarted the local k8s.
> 
> You didn't say that you upgraded RKE2, you said that you upgraded Rancher. Which did you do? Upgrading Rancher will not change anything about the local cluster, it will not upgrade RKE2 or restart any of its components.

Sorry if my references are not accurate, is rancher not rke2? Isn't RKE2 just the preferred K8s distro? We install rancher following this [documentation for it](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster), using the [rke2 install documentation](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher).

> > There was no extra load on any server or host. Why would etcd corrupt because of server IO load?
> > I can no longer go back that far to check the logs, as the logs for 3 weeks ago have already rolled over.
> 
> If you don't have logs or perf data, how can you say there was no extra load? Upgrading Rancher _will_ cause a spike in load as all the components are restarted and trigger updates to reconcile configurations for the new version. These operations put load on the apiserver and datastore.

I do not have them easily available today, but I did then. And my notes state there was hardly any consumption on the nodes that upgraded.

**Comment by brandond** [comment]
> is rancher not rke2

No. Rancher is a web UI and set of controllers and various tools for managing Kubernetes clusters.

RKE2 is a Kubernetes distribution. K3s, kubeadm, microk8s, EKS, GKE, and so on are other Kubernetes distributions. They provide the components (etcd, apiserver kubelet, and so on) that work together to provide a functional Kubernetes cluster that Rancher can be installed to.

Both products (rancher and rke2) were created by a company named Rancher, which was acquired by SUSE several years ago.

**Comment by johnwc** [comment]
> etcd cluster join failed: duplicate node name found, please use a unique name for this node

Getting this when running those commands, what do I need to run to remove the node from etcd? I am assuming needs to be run on one of the other nodes.

**Comment by brandond** [comment]
If you're seeing that, then run `kubectl delete node NODENAME` on one of the other two still-functional nodes. Once the node is deleted you should be able to rejoin it.

**Comment by johnwc** [comment]
Ok, that got it back online and responding, thank you. I completely forgot I could have also deleted the node from within rancher UI. 🤦‍♂️ Its now showing as `Cordoned` in the UI, how long should it take to go back to `Active`?

> Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".

And... whoever wrote that in the code needs a beer bought for them... lol That is hilarious!

**Comment by brandond** [comment]
Hmm I'm not sure why it would be cordoned. Is there an upgrade job running against that node for some reason?

Regardless, you should be able to `kubectl uncordon` that node from the CLI.

**Comment by johnwc** [comment]
It uncondoned itself after a bit of time. It may have been finishing the original update that it failed on.
