### ISSUE TITLE
Nvidia gpu support with containerd

### ISSUE THREAD

**Issue by xhejtman** [rancher/rke2#822]
Hello,

it there any working nvidia support with rke2 cluster and containerd runtime?

nvidia-docker2 it not applicable here.

I found gpu-operator, however, it does not work out of the box, validation failing. I found https://github.com/k3s-io/k3s/issues/2931 a notice, that it won't work with rke2: https://github.com/NVIDIA/gpu-operator (seems like it would be incompatible with k3s/rke2 because they supervise their containerd process and stop/restart when containerd stops, thus nullifying the utility of the operator).

so is there anything else what to try to get it work?

**Comment by bgulla** [comment]
I have this working using the containerd runtime + rke2.

https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/
https://gist.github.com/bgulla/3b725f0eea54fdd49f4d7066e16b1d89

The rancher federal team are preparing a blog post on how to do this with RKE2 in the next few weeks but this should get you started.

**Comment by xhejtman** [comment]
Thanks, it seems to be working. For ubuntu 20.04, this is the only needed change:
## RKE2 Instructions
mkdir -p /etc/rancher/rke2
echo "container-runtime-endpoint: unix:///run/containerd/containerd.sock" > /etc/rancher/rke2/config.yaml

**Comment by bgulla** [comment]
Great. Please close this issue if you’d like.

**Comment by ncoonrod** [comment]
Unfortunately the instructions at https://gist.github.com/bgulla/3b725f0eea54fdd49f4d7066e16b1d89 do not work.

Same with
`mkdir -p /etc/rancher/rke2
echo "container-runtime-endpoint: unix:///run/containerd/containerd.sock" > /etc/rancher/rke2/config.yaml`

I'm using Ubuntu 20.04.2 amd64, I've installed nvidia-docker according to their instructions and have containerd version 1.4.6 installed. rke2-server will not boot and crashes with:
```
time="2021-06-17T16:30:22-07:00" level=warning msg="not running in CIS mode"
time="2021-06-17T16:30:22-07:00" level=info msg="Starting rke2 v1.20.7+rke2r2 (ea6514775f816b0b4972f832de7d98eba8dff55c)"
time="2021-06-17T16:30:22-07:00" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
time="2021-06-17T16:30:22-07:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,rke2 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction,PodSecurityPolicy --encryption-provider-config=/var/lib/rancher/rke2/server/cred/encryption-config.json --etcd-cafile=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/rke2/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/rke2/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/rke2/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.key"
time="2021-06-17T16:30:22-07:00" level=info msg="Running kube-scheduler --address=127.0.0.1 --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig --port=10251 --profiling=false --secure-port=0"
time="2021-06-17T16:30:22-07:00" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/rke2/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/rke2/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/rke2/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/rke2/server/tls/service.key --use-service-account-credentials=true"
time="2021-06-17T16:30:22-07:00" level=info msg="Node token is available at /var/lib/rancher/rke2/server/token"
time="2021-06-17T16:30:22-07:00" level=info msg="To join node to cluster: rke2 agent -s https://192.168.1.181:9345 -t ${NODE_TOKEN}"
time="2021-06-17T16:30:22-07:00" level=info msg="Wrote kubeconfig /etc/rancher/rke2/rke2.yaml"
time="2021-06-17T16:30:22-07:00" level=info msg="Run: rke2 kubectl"
time="2021-06-17T16:30:22-07:00" level=info msg="Waiting for cloudcontroller rbac role to be created"
time="2021-06-17T16:30:22-07:00" level=info msg="Cluster-Http-Server 2021/06/17 16:30:22 http: TLS handshake error from 127.0.0.1:41190: remote error: tls: bad certificate"
time="2021-06-17T16:30:22-07:00" level=info msg="Cluster-Http-Server 2021/06/17 16:30:22 http: TLS handshake error from 127.0.0.1:41196: remote error: tls: bad certificate"
time="2021-06-17T16:30:22-07:00" level=info msg="certificate CN=squiggler signed by CN=rke2-server-ca@1623831173: notBefore=2021-06-16 08:12:53 +0000 UTC notAfter=2022-06-17 23:30:22 +0000 UTC"
time="2021-06-17T16:30:22-07:00" level=info msg="certificate CN=system:node:squiggler,O=system:nodes signed by CN=rke2-client-ca@1623831173: notBefore=2021-06-16 08:12:53 +0000 UTC notAfter=2022-06-17 23:30:22 +0000 UTC"
time="2021-06-17T16:30:22-07:00" level=info msg="Module overlay was already loaded"
time="2021-06-17T16:30:22-07:00" level=info msg="Module nf_conntrack was already loaded"
time="2021-06-17T16:30:22-07:00" level=info msg="Module br_netfilter was already loaded"
time="2021-06-17T16:30:22-07:00" level=info msg="Module iptable_nat was already loaded"
time="2021-06-17T16:30:22-07:00" level=info msg="Runtime image index.docker.io/rancher/rke2-runtime:v1.20.7-rke2r2 bin and charts directories already exist; skipping extract"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-kube-proxy.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rancher-vsphere-cpi.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-canal.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rancher-vsphere-csi.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-cilium.yaml to set cluster configuration values"
time="2021-06-17T16:30:22-07:00" level=info msg="Connecting to proxy" url="wss://127.0.0.1:9345/v1-rke2/connect"
time="2021-06-17T16:30:22-07:00" level=info msg="Handling backend connection request [squiggler]"
time="2021-06-17T16:30:22-07:00" level=info msg="Running kubelet --address=0.0.0.0 --alsologtostderr=false --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix://unix:///run/containerd/containerd.sock --container-runtime=remote --containerd=unix:///run/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=squiggler --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --kubelet-cgroups=/rke2 --log-file-max-size=50 --log-file=/var/lib/rancher/rke2/agent/logs/kubelet.log --logtostderr=false --network-plugin=cni --node-labels= --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --stderrthreshold=FATAL --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key"
Flag --volume-plugin-dir has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --file-check-frequency has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --sync-frequency has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --authentication-token-webhook has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --eviction-minimum-reclaim has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --healthz-bind-address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --kubelet-cgroups has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --tls-cert-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --tls-private-key-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
F0617 16:30:22.490232   19525 server.go:269] failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000e3e301, 0xc00030dc00, 0xde, 0xfb)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x6f73e40, 0xc000000003, 0x0, 0x0, 0xc000e50150, 0x6debc4c, 0x9, 0x10d, 0x410900)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x6f73e40, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000d152f0, 0x1, 0x1)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/klog/v2.Fatal(...)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000d46580, 0xc00004e250, 0x23, 0x23)
	/go/src/kubernetes/cmd/kubelet/app/server.go:269 +0x845
github.com/spf13/cobra.(*Command).execute(0xc000d46580, 0xc00004e250, 0x23, 0x23, 0xc000d46580, 0xc00004e250)
	/go/src/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d46580, 0x1689827ef3fac161, 0x6f73a00, 0x4088e5)
	/go/src/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	cmd/kubelet/kubelet.go:41 +0xe5

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x6f73e40)
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 182 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000112a00)
	/go/src/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
	/go/src/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 83 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc00070d190, 0xc000000000)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00070d180)
	/usr/local/go/src/sync/cond.go:56 +0x9d
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0000b8540, 0x0, 0x0, 0x3e4b700)
	/go/src/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:145 +0x89
k8s.io/client-go/transport.(*dynamicClientCert).processNextWorkItem(0xc00070d1c0, 0x203000)
	/go/src/kubernetes/vendor/k8s.io/client-go/transport/cert_rotation.go:156 +0x66
k8s.io/client-go/transport.(*dynamicClientCert).runWorker(0xc00070d1c0)
	/go/src/kubernetes/vendor/k8s.io/client-go/transport/cert_rotation.go:151 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00017a010)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00017a010, 0x507fa80, 0xc000a0c000, 0x1, 0xc0000c40c0)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00017a010, 0x3b9aca00, 0x0, 0xc000634001, 0xc0000c40c0)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00017a010, 0x3b9aca00, 0xc0000c40c0)
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/client-go/transport.(*dynamicClientCert).Run
	/go/src/kubernetes/vendor/k8s.io/client-go/transport/cert_rotation.go:140 +0x205
```

**Comment by ncoonrod** [comment]
Fixed the issue. Turns out, the sed command in the instructions was pointing to the wrong config file. You must comment out `disabled_plugins = ["cri"]` in `/etc/containerd/config.toml`

Commenting out that line fixed the issue immediately. Thanks!

**Comment by ziye-dm** [comment]
Hi, I tried https://github.com/rancher/rke2/issues/822#issuecomment-809490964
> I have this working using the containerd runtime + rke2.
> 
> https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/
> https://gist.github.com/bgulla/3b725f0eea54fdd49f4d7066e16b1d89
> 
> The rancher federal team are preparing a blog post on how to do this with RKE2 in the next few weeks but this should get you started.

or https://github.com/rancher/rke2/issues/822#issuecomment-809748372

> Thanks, it seems to be working. For ubuntu 20.04, this is the only needed change:
> 
> ## RKE2 Instructions
> mkdir -p /etc/rancher/rke2
> echo "container-runtime-endpoint: unix:///run/containerd/containerd.sock" > /etc/rancher/rke2/config.yaml

but all meet the same problem:
```
$ kubectl logs gpu-operator-6b5666bb8b-9m947
...
2021-07-14T08:05:53.698Z        INFO    controllers.ClusterPolicy       Found Resource  {"Service": "nvidia-dcgm-exporter", "Namespace": "gpu-operator-resources"}
2021-07-14T08:05:53.698Z        INFO    controllers.ClusterPolicy       Could not get any nodes to match nvidia.com/gpu.present label   {"Request.Namespace": "default", "Request.Name": "Node", "ERROR": ""}
2021-07-14T08:05:53.698Z        INFO    controllers.ClusterPolicy       Failed to apply transformation 'nvidia-dcgm-exporter' with error: 'ERROR: Could not find kernel full version: ('', '')' {"Daemonset": "nvidia-dcgm-exporter"}
2021-07-14T08:05:53.698Z        INFO    controllers.ClusterPolicy       Could not pre-process   {"DaemonSet": "nvidia-dcgm-exporter", "Namespace": "gpu-operator-resources", "Error": "ERROR: Could not find kernel full version: ('', '')"}
2021-07-14T08:05:53.699Z        ERROR   controller-runtime.manager.controller.clusterpolicy-controller  Reconciler error        {"name": "cluster-policy", "namespace": "", "error": "ERROR: Could not find kernel full version: ('', '')"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:301
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99
```
Any idea??

**Comment by ziye-dm** [comment]
I just made `gpu-operator` working with RKE2's containerd.
Here is my solution:
```
  if grep -q 'data-dir' /etc/rancher/rke2/config.yaml; then
    DATA_DIR=$(grep 'data-dir' /etc/rancher/rke2/config.yaml | awk '{print $2}')
  else
    DATA_DIR=/var/lib/rancher/rke2
  fi
  # Customize containerd config:
  # https://github.com/rancher/rke2/blob/master/docs/advanced.md#configuring-containerd
  # NOTE: Upgrade to version 2 config or the nvidia toolkit will fail:
  # https://github.com/NVIDIA/gpu-operator/issues/143#issuecomment-778194641
  CONTAINERD_CONFIG=$DATA_DIR/agent/etc/containerd/config.toml.tmpl
  echo "### Rewrite the config of containerd:"
  cat <<EOF | sudo tee $CONTAINERD_CONFIG
version = 2
[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    enable_selinux = false
    sandbox_image = "index.docker.io/rancher/pause:3.2"
    stream_server_address = "127.0.0.1"
    stream_server_port = "10010"
    [plugins."io.containerd.grpc.v1.cri".containerd]
      disable_snapshot_annotations = true
      snapshotter = "overlayfs"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.internal.v1.opt"]
    path = "/data/rancher/rke2/agent/containerd"
EOF
  CONTAINERD_SOCKET=/run/k3s/containerd/containerd.sock

  echo "### Install NVIDIA GPU Operator ..."
  # https://github.com/NVIDIA/gpu-operator/issues/174#issuecomment-829377008
  helm install --wait --generate-name \
    nvidia/gpu-operator $HELM_OPTIONS \
    --set operator.defaultRuntime=containerd \
    --set toolkit.env[0].name=CONTAINERD_CONFIG \
    --set toolkit.env[0].value=$CONTAINERD_CONFIG \
    --set toolkit.env[1].name=CONTAINERD_SOCKET \
    --set toolkit.env[1].value=$CONTAINERD_SOCKET \
    --set toolkit.env[2].name=CONTAINERD_RUNTIME_CLASS \
    --set toolkit.env[2].value=nvidia \
    --set toolkit.env[3].name=CONTAINERD_SET_AS_DEFAULT \
    --set-string toolkit.env[3].value=true
```

**Comment by ktarplee** [comment]
> I have this working using the containerd runtime + rke2.
> 
> https://developer.nvidia.com/blog/announcing-containerd-support-for-the-nvidia-gpu-operator/
> https://gist.github.com/bgulla/3b725f0eea54fdd49f4d7066e16b1d89
> 
> The rancher federal team are preparing a blog post on how to do this with RKE2 in the next few weeks but this should get you started.

@bgulla Did that blog post ever get created?  I would really like to read it.  We are still struggling to get RKE2 to work with NVIDIA GPU support.

**Comment by ktarplee** [comment]
We were able to get GPUs on RKE2 to work with the containerd provided by RKE2 on Ubuntu 20.04 LTS by doing the following.  We ran `apt install nvidia-container-runtime`.  We simply added a containerd template file at `/var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl`.

```toml
[plugins.opt]
  path = "/var/lib/rancher/rke2/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  sandbox_image = "index.docker.io/rancher/pause:3.2"

[plugins.cri.containerd]
  default_runtime_name = "nvidia"
  disable_snapshot_annotations = true
  snapshotter = "overlayfs"


[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins.cri.containerd.runtimes.nvidia]
  base_runtime_spec = ""
  container_annotations = []
  pod_annotations = []
  privileged_without_host_devices = false
  runtime_engine = ""
  runtime_root = ""
  runtime_type = "io.containerd.runc.v2"

  [plugins.cri.containerd.runtimes.nvidia.options]
     BinaryName = "/usr/bin/nvidia-container-runtime"
     CriuImagePath = ""
     CriuPath = ""
     CriuWorkPath = ""
     IoGid = 0
     IoUid = 0
     NoNewKeyring = false
     NoPivotRoot = false
     Root = ""
     ShimCgroup = ""
     SystemdCgroup = false
```

We did not use the gpu-operator but rather deployed the nvidia-device-plugin directly to enable GPU support.

**Comment by ktarplee** [comment]
Looks like k3s has a [pull request](https://github.com/k3s-io/k3s/pull/3890/files) to integrate GPU support into the internal containerd by automating the process of modifying config.toml.tmpl.  Maybe the same can be done for rke2.
@xhejtman You might be interested in the fact that GPUs do work with the integrated containerd in rke2 (see my above comment).

**Comment by xhejtman** [comment]
@ktarplee the gpu operator works for us with rke2, we just need at use external containerd and set containerd socket into rke2 config. Should it work with the gpu operator as well?

**Comment by ziye-dm** [comment]
> @ktarplee the gpu operator works for us with rke2, we just need at use external containerd and set containerd socket into rke2 config. Should it work with the gpu operator as well?

Hi it works. All I did is to upgrade the original config to version 2 and store it as `config.toml.tmpl`.
Check https://github.com/rancher/rke2/issues/822#issuecomment-880545876. I placed the useful link with codes also.

**Comment by turowicz** [comment]
Any official info for this?
