### ISSUE TITLE
Scaling out and in breaks api (etcd?) server

### ISSUE THREAD

**Issue by alex-petrov-vt** [rancher/rke2#824]
I have an rke2 cluster running in AWS with 3 masters and certain number of workers. I'm trying to implement a zero downtime update of the underlying os (which is rhel7 in this case). The idea is to update a launch template for the autoscaling group, then double the autoscaling group size (+-1 to have odd number of masters), cordon and drain old nodes, and then shrink the autoscaling group back to its original size. The expansion part works well with new server nodes joining the cluster correctly but when I try to scale the autoscaling group back to its original size API server becomes unresponsive and returns 503. Looking at logs and error messages, it seems that etcd servers become unresponsive.  Here's one of the responses for trying to do kubectl -v=8 get nodes:
```
I0329 19:40:04.138726    3028 round_trippers.go:422] GET https://internal-big-bang-0-klx-rke2-cp-2073511714.us-gov-west-1.elb.amazonaws.com:6443/api/v1/nodes?limit=500
I0329 19:40:04.138752    3028 round_trippers.go:429] Request Headers:
I0329 19:40:04.138760    3028 round_trippers.go:433]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
I0329 19:40:04.138769    3028 round_trippers.go:433]     User-Agent: kubectl/v1.20.5 (linux/amd64) kubernetes/6b1d87a
I0329 19:40:25.097700    3028 round_trippers.go:448] Response Status: 500 Internal Server Error in 20958 milliseconds
I0329 19:40:25.097726    3028 round_trippers.go:451] Response Headers:
I0329 19:40:25.097736    3028 round_trippers.go:454]     Date: Mon, 29 Mar 2021 19:40:25 GMT
I0329 19:40:25.097743    3028 round_trippers.go:454]     Cache-Control: no-cache, private
I0329 19:40:25.097749    3028 round_trippers.go:454]     Content-Type: application/json
I0329 19:40:25.097754    3028 round_trippers.go:454]     Content-Length: 122
I0329 19:40:25.097791    3028 request.go:1107] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"etcdserver: request timed out","code":500}
I0329 19:40:25.098248    3028 helpers.go:216] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "etcdserver: request timed out",
  "code": 500
}]
F0329 19:40:25.098283    3028 helpers.go:115] Error from server: etcdserver: request timed out
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc0009aa200, 0x5f, 0x1f7)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2a74040, 0xc000000003, 0x0, 0x0, 0xc000633810, 0x28546e3, 0xa, 0x73, 0x40e200)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2a74040, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc0009a65e0, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc00057e540, 0x31, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1cf69a0, 0xc0009ae2e0, 0x1bbf138)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:177 +0x8b5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc00047a2c0, 0xc000102740, 0x1, 0x2)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:167 +0x159
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00047a2c0, 0xc000102720, 0x2, 0x2, 0xc00047a2c0, 0xc000102720)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c4b00, 0xc00007c180, 0xc00003a080, 0x4)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a74040)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 18 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bbf058, 0x1cf4520, 0xc00051dd40, 0x1, 0xc000088b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bbf058, 0x12a05f200, 0x0, 0x1, 0xc000088b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bbf058, 0x12a05f200, 0xc000088b40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 138 [IO wait]:
internal/poll.runtime_pollWait(0x7f98af57c258, 0x72, 0x1cf75e0)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0005dd798, 0x72, 0x1cf7500, 0x2880610, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0005dd780, 0xc0008ae000, 0x92c, 0x92c, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0005dd780, 0xc0008ae000, 0x92c, 0x92c, 0x203000, 0x65413b, 0xc0008ac160)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0001068d8, 0xc0008ae000, 0x92c, 0x92c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc00096dca0, 0xc0008ae000, 0x92c, 0x92c, 0x94, 0x8d0, 0xc00085f708)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0008ac280, 0x1cf2f20, 0xc00096dca0, 0x40b685, 0x18ecea0, 0x1a555a0)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0008ac000, 0x1cf59c0, 0xc0001068d8, 0x5, 0xc0001068d8, 0x83)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0008ac000, 0x0, 0x0, 0xc0008b2280)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0008ac000, 0xc0008b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc0003634a0, 0xc0006fe818, 0x9, 0x9, 0xc000363500, 0xc00085fd18, 0x1bbfe00)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1cf2d40, 0xc0003634a0, 0xc0006fe818, 0x9, 0x9, 0x9, 0xc0009a6050, 0xc00004c070, 0x0)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc0006fe818, 0x9, 0x9, 0x1cf2d40, 0xc0003634a0, 0x0, 0x0, 0xc000965980, 0xc00085fdd0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0006fe7e0, 0xc000965980, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00085ffa8, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00071d080)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5
```

Is my idea for doing the update incorrect in the context of rke2? I thought I was following a pretty standard practice for doing OS updates for kubernetes clusters. Has anyone encountered this issue before?

Thanks!

**Comment by alex-petrov-vt** [comment]
It seems that in my script I've forgotten to actually delete the nodes from the cluster using kubectl delete node, so etcd never updated its internal config
