### ISSUE TITLE
Upgrade from v1.20.4 to v1.20.5 rc fails while using curl method

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/rke2#828]
**Environment Info:**
rke2 version v1.20.4+rke2r1

**Node(s) CPU architecture, OS, and Version:**
Centos 8.2, SELinux Enabled

**Cluster Configuration:**
Single node cluster

**Describe the bug:**
Upgrade from v1.20.4+rke2r1 to v1.20.5-rc1+rke2r1 fails 

**Steps To Reproduce:**
1. Install rke2 version v1.20.4+rke2r1  on Centos with SELinux enabled using the following command
```
$ cat /etc/rancher/rke2/config.yaml 
selinux: true

$ curl -sfL https://get.rke2.io| sudo INSTALL_RKE2_VERSION=v1.20.4+rke2r1 INSTALL_RKE2_CHANNEL=latest sh -
```
2. Upgrade to v1.20.5-rc1_rke2r1 as below
```
curl -sfL https://get.rke2.io| sudo INSTALL_RKE2_VERSION=v1.20.5-rc1+rke2r1 INSTALL_RKE2_CHANNEL=testing sh -
```

**Expected behavior:**
Upgrade should be successful

**Actual behavior:**
Upgrade fails with below logs

**Additional info:**
```
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: F0330 17:59:28.189987   20050 server.go:162] listen tcp 0.0.0.0:10250: bind: address already in use
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: goroutine 819 [running]:
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/klog/v2.stacks(0xc0003a6d01, 0xc0001f2500, 0x64, 0x249)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/klog/v2.(*loggingT).output(0x6f78dc0, 0xc000000003, 0x0, 0x0, 0xc0004a6a80, 0x6e029bf, 0x9, 0xa2, 0x410900)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/klog/v2.(*loggingT).printDepth(0x6f78dc0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0013ea4d0, 0x1, 0x1)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/klog/v2.(*loggingT).print(...)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/klog/v2.Fatal(...)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/kubernetes/pkg/kubelet/server.ListenAndServeKubeletServer(0x5168260, 0xc000a9e000, 0x5106400, 0xc000db0b60, 0xc000df1750, 0x10, 0x10, 0x280a, 0xc0004f2ff0, 0x50f7680, ...)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/pkg/kubelet/server/server.go:162 +0x4fa
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).ListenAndServe(0xc000a9e000, 0xc000df1750, 0x10, 0x10, 0x280a, 0xc0004f2ff0, 0x50f7680, 0xc000a2a060, 0xc001000100)
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/pkg/kubelet/kubelet.go:2226 +0xdb
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]:         /go/src/kubernetes/cmd/kubelet/app/server.go:1187 +0x226
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: goroutine 1 [select]:
Mar 30 17:59:28 ip-172-31-46-25.us-east-2.compute.internal rke2[19745]: k8s.io/kubernetes/cmd/kubelet/app.run(0x5104d40, 0xc0002eb240, 0xc00056d100, 0xc0004ea600, 0x7ff739ea3e00, 0xc0004424c0, 0x4a30aaf, 0xc)
```

Note: Above issue is not seen on Ubuntu 20.04. Upgrade can be successfully completed from v1.20.4+rke2r1 to v1.20.5-rc1+rke2r1

**Comment by ShylajaDevadiga** [comment]
Validated using rke2 version v1.20.5-rc2+rke2r1, upgrade from v1.20.4+rke2r1 to v1.20.5-rc2+rke2r1 is successful on centos8.2 selinux enabled nodes
```

$ kubectl get nodes 
NAME                                         STATUS   ROLES                       AGE     VERSION
ip-172-31-14-25.us-east-2.compute.internal   Ready    control-plane,etcd,master   8m35s   v1.20.4+rke2r1
ip-172-31-15-35.us-east-2.compute.internal   Ready    <none>                      33s     v1.20.4+rke2r1
$ sudo cat /var/lib/rancher/rke2/agent/etc/containerd/config.toml|grep selinux
  enable_selinux = true

$ kubectl get nodes 
NAME                                         STATUS   ROLES                       AGE     VERSION
ip-172-31-14-25.us-east-2.compute.internal   Ready    control-plane,etcd,master   13m     v1.20.5-rc2+rke2r1
ip-172-31-15-35.us-east-2.compute.internal   Ready    <none>                      5m43s   v1.20.5-rc2+rke2r1
```

**Comment by rancher-max** [comment]
Reopening as this also applies when upgrading via system-upgrade-controller

**Comment by rancher-max** [comment]
Validated this is fixed now on rc3. Ensured can upgrade via SUC or rancher on Centos7 + selinux, Centos8 + selinux, SLES, and Ubuntu.
