### ISSUE TITLE
rke2 server --cluster-reset doesn't work

### ISSUE THREAD

**Issue by ryanelliottsmith** [rancher/rke2#934]
**Environmental Info:**
RKE2 Version:  v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)

Node(s) CPU architecture, OS, and Version: 
x64 ubuntu 20.04

Cluster Configuration:
3x server
**Describe the bug:**
--cluster-reset doesn't appear to work

**Steps To Reproduce:**
1. Install rke2 server on initial node with `curl -sfL https://get.rke2.io | sh -`
2. Take node-token and install 2 additional nodes as per [HA docs](https://docs.rke2.io/install/ha/), using initial node as the server address
3. Wait for cluster to stabilize and all 3 nodes to show as `Ready`
4. Force etcd quorum loss by shutting down the 2 additional nodes
5. stop rke2-server and attempt to reset cluster to a single-node cluster on the initial node with `rke2 server --cluster-reset`

**Expected behavior:**

Cluster should come back as a single-node cluster using existing etcd data

**Actual behavior:**
rke2 doesn't appear to attempt to reset etcd and instead starts as normal:
```
# systemctl stop rke2-server
# rke2 server --cluster-reset
WARN[0000] not running in CIS mode
INFO[0000] Runtime image index.docker.io/rancher/rke2-runtime:v1.20.6-rke2r1 bin and charts directories already exist; skipping extract
INFO[0000] Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-kube-proxy.yaml to apply --system-default-registry modifications
INFO[0000] Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml to apply --system-default-registry modifications
INFO[0000] Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-canal.yaml to apply --system-default-registry modifications
INFO[0000] Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml to apply --system-default-registry modifications
INFO[0000] Updated HelmChart /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml to apply --system-default-registry modifications
INFO[0000] Starting rke2 v1.20.6+rke2r1 (da4fc2f8ca6bc5fe7f918c885848c087e8029773)
INFO[0000] Managed etcd cluster bootstrap already complete and initialized
INFO[0000] Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,rke2 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction,PodSecurityPolicy --encryption-provider-config=/var/lib/rancher/rke2/server/cred/encryption-config.json --etcd-cafile=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/rke2/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/rke2/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key --profiling=false --proxy-client-cert-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/rke2/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.key
INFO[0000] Running kube-scheduler --address=127.0.0.1 --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig --port=10251 --profiling=false --secure-port=0
INFO[0000] Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --cluster-signing-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/rke2/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/rke2/server/tls/service.key --use-service-account-credentials=true
INFO[0000] Node token is available at /var/lib/rancher/rke2/server/token
INFO[0000] To join node to cluster: rke2 agent -s https://10.199.10.211:9345 -t ${NODE_TOKEN}
INFO[0000] etcd data store connection OK
INFO[0000] Waiting for API server to become available
INFO[0000] Wrote kubeconfig /etc/rancher/rke2/rke2.yaml
INFO[0000] Run: rke2 kubectl
INFO[0000] Module overlay was already loaded
INFO[0000] Module nf_conntrack was already loaded
INFO[0000] Module br_netfilter was already loaded
INFO[0000] Module iptable_nat was already loaded
INFO[0000] Cluster-Http-Server 2021/04/29 23:16:28 http: TLS handshake error from 127.0.0.1:49916: remote error: tls: bad certificate
INFO[0000] Cluster-Http-Server 2021/04/29 23:16:28 http: TLS handshake error from 127.0.0.1:49922: remote error: tls: bad certificate
INFO[0000] certificate CN=ip-10-199-10-211 signed by CN=rke2-server-ca@1619737597: notBefore=2021-04-29 23:06:37 +0000 UTC notAfter=2022-04-29 23:16:28 +0000 UTC
INFO[0000] certificate CN=system:node:ip-10-199-10-211,O=system:nodes signed by CN=rke2-client-ca@1619737597: notBefore=2021-04-29 23:06:37 +0000 UTC notAfter=2022-04-29 23:16:28 +0000 UTC
INFO[0000] Logging containerd to /var/lib/rancher/rke2/agent/containerd/containerd.log
INFO[0000] Running containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/containerd
INFO[0001] Containerd is now running

INFO[0020] Connecting to proxy                           url="wss://127.0.0.1:9345/v1-rke2/connect"
INFO[0020] Waiting for cloudcontroller rbac role to be created
INFO[0020] Handling backend connection request [ip-10-199-10-211]
INFO[0020] Running kubelet --address=0.0.0.0 --alsologtostderr=false --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=ip-10-199-10-211 --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --kubelet-cgroups=/rke2 --log-file-max-size=50 --log-file=/var/lib/rancher/rke2/agent/logs/kubelet.log --logtostderr=false --node-labels= --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --resolv-conf=/run/systemd/resolve/resolv.conf --serialize-image-pulls=false --stderrthreshold=FATAL --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key
Flag --volume-plugin-dir has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --anonymous-auth has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --authentication-token-webhook has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard CLI deprecation timeline before being removed.
Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --eviction-minimum-reclaim has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --healthz-bind-address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --kubelet-cgroups has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --read-only-port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --tls-cert-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --tls-private-key-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
INFO[0034] Waiting for API server to become available
INFO[0050] Waiting for cloudcontroller rbac role to be created
INFO[0068] Waiting for API server to become available
INFO[0080] Waiting for cloudcontroller rbac role to be created
INFO[0080] Waiting for kubelet to be ready on node ip-10-199-10-211: etcdserver: request timed out
INFO[0102] Waiting for API server to become available
INFO[0110] Waiting for cloudcontroller rbac role to be created
INFO[0136] Waiting for API server to become available
INFO[0140] Waiting for cloudcontroller rbac role to be created
{"level":"warn","ts":"2021-04-29T23:19:08.220Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
ERRO[0160] Failed to check local etcd status for learner management: context deadline exceeded
INFO[0172] Waiting for API server to become available
{"level":"warn","ts":"2021-04-29T23:19:23.220Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
ERRO[0175] Failed to check local etcd status for learner management: context deadline exceeded
{"level":"warn","ts":"2021-04-29T23:19:38.220Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
ERRO[0190] Failed to check local etcd status for learner management: context deadline exceeded
{"level":"warn","ts":"2021-04-29T23:19:53.220Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///https://127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
ERRO[0205] Failed to check local etcd status for learner management: context deadline exceeded
INFO[0205] Waiting for cloudcontroller rbac role to be created
INFO[0206] Waiting for API server to become available
```

**Additional context / logs:**
Reset is performed on the initial node

gz#16337

**Comment by dverbeek84** [comment]
I can verify that i also got this issue. Adding --cluster-reset-restore-path seems to do somthing. But the cluster is sort of unable to recover.

**Comment by ShylajaDevadiga** [comment]
Validated the fix using commit rke2 version v1.21.0-dev+1c910cc8
Created a three node cluster
```

ubuntu@ip-172-31-8-250:~$ kubectl get nodes
NAME              STATUS   ROLES                       AGE     VERSION
ip-172-31-1-231   Ready    control-plane,etcd,master   10m     v1.21.0-dev+1c910cc8
ip-172-31-5-54    Ready    control-plane,etcd,master   8m32s   v1.21.0-dev+1c910cc8
ip-172-31-8-250   Ready    control-plane,etcd,master   15m     v1.21.0-dev+1c910cc8

sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
760f7eac253c5e36, started, ip-172-31-1-231-0138bc4f, https://172.31.1.231:2380, https://172.31.1.231:2379
7f10f258f6716c10, started, ip-172-31-8-250-e3aa031d, https://172.31.8.250:2380, https://172.31.8.250:2379
b1a7116790c16ecc, started, ip-172-31-5-54-2a4d7efd, https://172.31.5.54:2380, https://172.31.5.54:2379
```
Powerdown two nodes to force quorum loss
```
ubuntu@ip-172-31-8-250:~$ kubectl get nodes
^C
ubuntu@ip-172-31-8-250:~$ sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
Error:  dial tcp 127.0.0.1:2379: connect: connection refused
```
Stop and start rke2 service with cluster-reset flag

```
ubuntu@ip-172-31-8-250:~$  sudo systemctl stop rke2-server
ubuntu@ip-172-31-8-250:~$ sudo rke2 server --cluster-reset
```
Console logs show the expected cluset-reset flag
```
...
INFO[0335] Waiting for cloudcontroller rbac role to be created 
INFO[0336] etcd data store connection OK                
INFO[0336] Saving current etcd snapshot set to rke2-etcd-snapshots ConfigMap 
INFO[0336] Waiting for API server to become available   
INFO[0336] Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes 
```
Start service
```
ubuntu@ip-172-31-8-250:~$ sudo systemctl start rke2-server
```
First Node is available in etcd as well as in k8s cluster with other two nodes in NotReady State
```
sudo ETCDCTL_API=3 etcdclient.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
7f10f258f6716c10, started, ip-172-31-8-250-f7ad629b, https://172.31.8.250:2380, https://172.31.8.250:2379

ubuntu@ip-172-31-8-250:~$ kubectl get nodes
NAME              STATUS     ROLES                       AGE   VERSION
ip-172-31-1-231   NotReady   control-plane,etcd,master   44m   v1.21.0-dev+1c910cc8
ip-172-31-5-54    NotReady   control-plane,etcd,master   42m   v1.21.0-dev+1c910cc8
ip-172-31-8-250   Ready      control-plane,etcd,master   49m   v1.21.0-dev+1c910cc8

ubuntu@ip-172-31-8-250:~$ kubectl delete node ip-172-31-1-231
node "ip-172-31-1-231" deleted
ubuntu@ip-172-31-8-250:~$ kubectl delete node ip-172-31-5-54
node "ip-172-31-5-54" deleted

ubuntu@ip-172-31-8-250:~$ kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-8-250   Ready    control-plane,etcd,master   49m   v1.21.0-dev+1c910cc8
```
Keeping issue open to validate when rc is available.

**Comment by ShylajaDevadiga** [comment]
Closing this issue as validated. Will re-validate with rc when available

**Comment by ShylajaDevadiga** [comment]
Reopening due to error seen while validating using rc. Related issue https://github.com/rancher/rke2/issues/1052
```
$ sudo rke2 server --cluster-reset
WARN[0000] not running in CIS mode                      
INFO[0000] starting kubelet to clean up old static pods 
INFO[0005] kubelet Exited: exec: "kubelet": executable file not found in $PATH, exiting Containerd 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4be89b]

goroutine 1 [running]:
os.(*Process).signal(0x0, 0x70cc4b8, 0x9be7958, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:63 +0x3b
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:135
os.(*Process).kill(...)
	/usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
	/usr/local/go/src/os/exec.go:120
github.com/rancher/rke2/pkg/rke2.removeOldPodManifests(0x66d7963, 0x15, 0xc000a7fdd0, 0x1, 0x0, 0x0)
	/source/pkg/rke2/rke2.go:224 +0xa3b
github.com/rancher/rke2/pkg/rke2.setup(0xc000c02f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/source/pkg/rke2/rke2.go:164 +0x8a5
github.com/rancher/rke2/pkg/rke2.Server(0xc000c02f20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/source/pkg/rke2/rke2.go:48 +0x6b
github.com/rancher/rke2/pkg/cli/cmds.ServerRun(0xc000c02f20, 0x0, 0x0)
	/source/pkg/cli/cmds/server.go:143 +0x98
github.com/urfave/cli.HandleAction(0x57f1f00, 0x68fece0, 0xc000c02f20, 0xc000c02f20, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x6693772, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x66da585, 0x15, 0xc001646a08, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc001a4fc00, 0xc0013b1080, 0x3, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
	/source/main.go:20 +0x714

```

**Comment by davidnuzik** [comment]
Should be resolved via https://github.com/rancher/rke2/issues/1052 and incoming v1.20.7+rke2r2 release.

**Comment by ShylajaDevadiga** [comment]
Validating on a single node cluster and three node cluster using v1.20.7-rc1+rke2r2 
OS: Ubuntu 20.04, Centos 8.2
Steps followed:

- Create a single node cluster

```
$ kubectl get nodes
NAME              STATUS   ROLES                       AGE    VERSION
ip-172-31-38-19   Ready    control-plane,etcd,master   3m8s   v1.20.7-rc1+rke2r2
```

- Verify cluster is up and nodes ready and pods running
- Stop rke2 service
```
$ sudo systemctl stop rke2-server
```
- Start rke2 server with cluster-reset
```
$ sudo rke2 server --cluster-reset -> returns to the prompt with restart without cluster-reset flag.
...
INFO[0085] Etcd is running, restart without --cluster-reset flag now. Backup and delete ${datadir}/server/db on each peer etcd server and rejoin the nodes 
```

- Start rke2 service with cluster-reset

```
$ sudo systemctl start rke2-server
```

- Verify node is up and pods are running

```
$ kubectl get nodes
NAME              STATUS   ROLES                       AGE   VERSION
ip-172-31-38-19   Ready    control-plane,etcd,master   16m   v1.20.7-rc1+rke2r2
```
On a three node setup

- Verify cluster is up and all 3 nodes ready and pods running
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-31-34-7     Ready    control-plane,etcd,master   2m46s   v1.20.7-rc1+rke2r2
ip-172-31-44-247   Ready    control-plane,etcd,master   119s    v1.20.7-rc1+rke2r2
ip-172-31-47-1     Ready    control-plane,etcd,master   24m     v1.20.7-rc1+rke2r2
```
```
$ sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
269a2b75ff3f2ff, started, ip-172-31-44-247-23bd7bba, https://172.31.44.247:2380, https://172.31.44.247:2379
2137050e35452024, started, ip-172-31-47-1-1bc271ce, https://172.31.47.1:2380, https://172.31.47.1:2379
6607ce5e5a273d52, started, ip-172-31-34-7-6d959a43, https://172.31.34.7:2380, https://172.31.34.7:2379
ubuntu@ip-172-31-47-1:~$ sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/serve
```
- Poweroff two nodes
```
$ sudo systemctl stop rke2-server on the node 1
$ sudo rke2 server --cluster-reset ->  returns to the prompt with restart without cluster-reset flag.
$ sudo systemctl start rke2-server
$ sudo ETCDCTL_API=3 etcdctl --cert /var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key /var/lib/rancher/rke2/server/tls/etcd/server-client.key --endpoints https://127.0.0.1:2379 --cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt member list
2137050e35452024, started, ip-172-31-47-1-f0bf8e68, https://172.31.47.1:2380, https://172.31.47.1:2379
```
```
$ kubectl get nodes
NAME               STATUS     ROLES                       AGE   VERSION
ip-172-31-34-7     NotReady   control-plane,etcd,master   16m   v1.20.7-rc1+rke2r2
ip-172-31-44-247   NotReady   control-plane,etcd,master   15m   v1.20.7-rc1+rke2r2
ip-172-31-47-1     Ready      control-plane,etcd,master   37m   v1.20.7-rc1+rke2r2
```

- Delete the two nodes thats in NotReady state from k8s cluster 
```
$ kubectl delete node ip-172-31-34-7 ip-172-31-44-247
node "ip-172-31-34-7" deleted
node "ip-172-31-44-247" deleted

$ kubectl get nodes
NAME             STATUS   ROLES                       AGE   VERSION
ip-172-31-47-1   Ready    control-plane,etcd,master   43m   v1.20.7-rc1+rke2r2
```

- Join new nodes or uninstall and reinstall to join back the two nodes
```
$ kubectl get nodes
NAME               STATUS   ROLES                       AGE     VERSION
ip-172-31-34-7     Ready    control-plane,etcd,master   2m33s   v1.20.7-rc1+rke2r2
ip-172-31-44-247   Ready    control-plane,etcd,master   117s    v1.20.7-rc1+rke2r2
ip-172-31-47-1     Ready    control-plane,etcd,master   48m     v1.20.7-rc1+rke2r2
```
